<? 
/* *******************************************************************************************************
MODUL NAME 			: IMASYS
FILE NAME 			: 
AUTHOR				: 
VERSION				: 1.0
MODIFICATION DOC	:
DESCRIPTION			: 
***************************************************************************************************** */

  /***
  * EntitySIUK-base class untuk mengimplementasikan tabel KBBR_BUKU_BESAR.
  * 
  ***/
  include_once("../WEB-INF-SIUK/classes/db/Entity.php");

  class KbbrBukuBesar extends EntitySIUK{ 

	var $query;
    /**
    * Class constructor.
    **/
    function KbbrBukuBesar()
	{
      $this->EntitySIUK(); 
    }
	
	function insert()
	{
		/*Auto-generate primary key(s) by next max value (integer) */
		//$this->setField("KD_BUKU_BESAR", $this->getNextId("KD_BUKU_BESAR","KBBR_BUKU_BESAR")); 		
		//'".$this->getField("FOTO")."',  FOTO,
		$str = "
				INSERT INTO KBBR_BUKU_BESAR (
				   KD_CABANG, KD_BUKU_BESAR, NM_BUKU_BESAR, 
				   TIPE_REKENING, POLA_ENTRY, GRUP_DTL_KODE, 
				   GRUP_LEVEL1, GRUP_LEVEL2, GRUP_LEVEL3, 
				   GRUP_LEVEL4, GRUP_LEVEL5, KD_BUKU_PUSAT, 
				   KD_POSTING_BB, KD_POSTING_SUB, KODE_VALUTA, 
				   COA_ID, KET_TAMBAHAN, KD_AKTIF, 
				   LAST_UPDATE_DATE, LAST_UPDATED_BY, PROGRAM_NAME) 
				VALUES ( '".$this->getField("KD_CABANG")."', '".$this->getField("KD_BUKU_BESAR")."', '".$this->getField("NM_BUKU_BESAR")."',
					'".$this->getField("TIPE_REKENING")."', '".$this->getField("POLA_ENTRY")."', '".$this->getField("GRUP_DTL_KODE")."',
					'".$this->getField("GRUP_LEVEL1")."', '".$this->getField("GRUP_LEVEL2")."', '".$this->getField("GRUP_LEVEL3")."',
					'".$this->getField("GRUP_LEVEL4")."', '".$this->getField("GRUP_LEVEL5")."', '".$this->getField("KD_BUKU_PUSAT")."',
					'".$this->getField("KD_POSTING_BB")."', '".$this->getField("KD_POSTING_SUB")."', '".$this->getField("KODE_VALUTA")."',
					'".$this->getField("COA_ID")."', '".$this->getField("KET_TAMBAHAN")."', '".$this->getField("KD_AKTIF")."',
					".$this->getField("LAST_UPDATE_DATE").", '".$this->getField("LAST_UPDATED_BY")."', '".$this->getField("PROGRAM_NAME")."'
				)";
				
		$this->id = $this->getField("KD_BUKU_BESAR");
		$this->query = $str;
		//echo $str;
		return $this->execQuery($str);
    }
	
	
	function callLapBukuBantu()
	{
        $str = "
				CALL PROSES_LAP_BUKU_BANTU('".$this->getField("BULAN")."', '".$this->getField("TAHUN")."')
		"; 
		$this->query = $str;
        return $this->execQuery($str);
    }		
	

    function update()
	{
		$str = "
				UPDATE KBBR_BUKU_BESAR
				SET    
					   KD_CABANG        = '".$this->getField("KD_CABANG")."',
					   KD_BUKU_BESAR    = '".$this->getField("KD_BUKU_BESAR")."',
					   NM_BUKU_BESAR    = '".$this->getField("NM_BUKU_BESAR")."',
					   TIPE_REKENING    = '".$this->getField("TIPE_REKENING")."',
					   POLA_ENTRY       = '".$this->getField("POLA_ENTRY")."',
					   GRUP_DTL_KODE    = '".$this->getField("GRUP_DTL_KODE")."',
					   GRUP_LEVEL1      = '".$this->getField("GRUP_LEVEL1")."',
					   GRUP_LEVEL2      = '".$this->getField("GRUP_LEVEL2")."',
					   GRUP_LEVEL3      = '".$this->getField("GRUP_LEVEL3")."',
					   GRUP_LEVEL4      = '".$this->getField("GRUP_LEVEL4")."',
					   GRUP_LEVEL5      = '".$this->getField("GRUP_LEVEL5")."',
					   KD_BUKU_PUSAT    = '".$this->getField("KD_BUKU_PUSAT")."',
					   KD_POSTING_BB    = '".$this->getField("KD_POSTING_BB")."',
					   KD_POSTING_SUB   = '".$this->getField("KD_POSTING_SUB")."',
					   KODE_VALUTA      = '".$this->getField("KODE_VALUTA")."',
					   COA_ID           = '".$this->getField("COA_ID")."',
					   KET_TAMBAHAN     = '".$this->getField("KET_TAMBAHAN")."',
					   KD_AKTIF         = '".$this->getField("KD_AKTIF")."',
					   LAST_UPDATE_DATE = ".$this->getField("LAST_UPDATE_DATE").",
					   LAST_UPDATED_BY  = '".$this->getField("LAST_UPDATED_BY")."',
					   PROGRAM_NAME     = '".$this->getField("PROGRAM_NAME")."'
				WHERE  KD_BUKU_BESAR = '".$this->getField("KD_BUKU_BESAR_ID")."'
			";//FOTO= '".$this->getField("FOTO")."',
		$this->query = $str;
		//echo $str;
		return $this->execQuery($str);
    }
	
	function delete()
	{
        $str = "DELETE FROM KBBR_BUKU_BESAR
                WHERE 
                  KD_BUKU_BESAR = '".$this->getField("KD_BUKU_BESAR")."'"; 
				  
		$this->query = $str;
        return $this->execQuery($str);
    }

    /** 
    * Cari record berdasarkan array parameter dan limit tampilan 
    * @param array paramsArray Array of parameter. Contoh array("id"=>"xxx","IJIN_USAHA_ID"=>"yyy") 
    * @param int limit Jumlah maksimal record yang akan diambil 
    * @param int from Awal record yang diambil 
    * @return boolean True jika sukses, false jika tidak 
    **/ 
    function selectByParams($paramsArray=array(),$limit=-1,$from=-1, $statement="", $order="ORDER BY KD_BUKU_BESAR DESC")
	{
		$str = "
				SELECT A.KD_CABANG, A.KD_BUKU_BESAR, NM_BUKU_BESAR, 
				NAMA_GROUP TIPE_REKENING, 
				CASE WHEN POLA_ENTRY = 0 THEN 'Buku Besar' 
					 WHEN POLA_ENTRY = 1 THEN 'Buku Besar & Kartu' 
					 WHEN POLA_ENTRY = 2 THEN 'Buku Besar & Pusat Biaya' 
					 WHEN POLA_ENTRY = 3 THEN 'Buku Besar, Kartu & Pusat Biaya' 
					 ELSE 'Buku Besar' 
				END POLA_ENTRY,
				POLA_ENTRY POLA_ENTRY_ID, 
				GRUP_DTL_KODE, CASE WHEN GRUP_DTL_KODE = 'D' THEN 'DETAIL' WHEN GRUP_DTL_KODE='H' THEN 'HEADER' END GRUP_DTL_KODE_DESC,
                GRUP_LEVEL1, GRUP_LEVEL2, GRUP_LEVEL3, 
                GRUP_LEVEL4, GRUP_LEVEL5, KD_BUKU_PUSAT, 
                KD_POSTING_BB, KD_POSTING_SUB, KODE_VALUTA, 
                COA_ID, KET_TAMBAHAN, A.KD_AKTIF, 
                A.LAST_UPDATE_DATE, A.LAST_UPDATED_BY, A.PROGRAM_NAME, B.ID_GROUP
                FROM KBBR_BUKU_BESAR A 
                LEFT JOIN KBBR_GROUP_REK B ON TIPE_REKENING = ID_GROUP
                WHERE 1 = 1
				"; 
		//, FOTO
		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$order;
		$this->query = $str;
		return $this->selectLimit($str,$limit,$from); 
    }

    function selectByParamsSimple($paramsArray=array(),$limit=-1,$from=-1, $statement="", $order="ORDER BY KD_BUKU_BESAR DESC")
	{
		$str = "
				SELECT A.KD_BUKU_BESAR, NM_BUKU_BESAR, 
				POLA_ENTRY POLA_ENTRY_ID
                FROM KBBR_BUKU_BESAR A 
                WHERE 1 = 1
				"; 
		//, FOTO
		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$order;
		$this->query = $str;
		
		return $this->selectLimit($str,$limit,$from); 
    }
	
	function selectByParamsBukuBesar($paramsArray=array(),$limit=-1,$from=-1, $statement="", $reqBulan="", $reqTahun="", $order="")
	{
		$str = "SELECT COA, KD_LEVEL2, NM_BUKU_BESAR, ROUND(SALDO_BULAN_LALU) SALDO_BULAN_LALU, DK_LALU, ROUND(DEBET) DEBET, ROUND(KREDIT) KREDIT, 
					DK_INI, ROUND(SALDO_BULAN_INI) SALDO_BULAN_INI, 
                    ROUND(DEBET_BI) DEBET_BI, ROUND(KREDIT_BI) KREDIT_BI 
                FROM
                ( SELECT COA, KD_LEVEL2, NM_BUKU_BESAR, DK_LALU, CASE WHEN SALDO_BULAN_LALU < 0 THEN ABS(SALDO_BULAN_LALU) ELSE SALDO_BULAN_LALU END SALDO_BULAN_LALU, 
					DEBET, KREDIT, CASE  WHEN SALDO_BULAN_LALU+DEBET-KREDIT < 0 THEN 'K' WHEN  SALDO_BULAN_LALU+DEBET-KREDIT > 0 THEN 'D' ELSE ' ' END DK_INI,
					CASE WHEN SALDO_BULAN_LALU+DEBET-KREDIT < 0 THEN ABS(SALDO_BULAN_LALU+DEBET-KREDIT) ELSE SALDO_BULAN_LALU+DEBET-KREDIT END SALDO_BULAN_INI, 
					DEBET_BI, KREDIT_BI 
				FROM 
				( SELECT COA_ID ||' - ' ||COA_NAME COA, KD_LEVEL2, NM_BUKU_BESAR, 
					CASE ".$reqBulan." WHEN 01 THEN P01_DEBET  WHEN 02 THEN P02_DEBET WHEN 03 THEN P03_DEBET WHEN 04 THEN P04_DEBET WHEN 05 THEN P05_DEBET 
					WHEN 06 THEN P06_DEBET WHEN 07 THEN P07_DEBET WHEN 08 THEN P08_DEBET  WHEN 09 THEN P09_DEBET WHEN 10 THEN P10_DEBET WHEN 11 THEN P11_DEBET 
					WHEN 12 THEN P12_DEBET WHEN 13 THEN P13_DEBET WHEN 14 THEN P14_DEBET WHEN 15 THEN P15_DEBET WHEN 16 THEN P16_DEBET END DEBET, 
					CASE ".$reqBulan." WHEN 01 THEN P01_KREDIT  WHEN 02 THEN P02_KREDIT WHEN 03 THEN P03_KREDIT WHEN 04 THEN P04_KREDIT WHEN 05 THEN P05_KREDIT 
					WHEN 06 THEN P06_KREDIT WHEN 07 THEN P07_KREDIT WHEN 08 THEN P08_KREDIT  WHEN 09 THEN P09_KREDIT WHEN 10 THEN P10_KREDIT WHEN 11 THEN P11_KREDIT 
					WHEN 12 THEN P12_KREDIT WHEN 13 THEN P13_KREDIT WHEN 14 THEN P14_KREDIT WHEN 15 THEN P15_KREDIT WHEN 16 THEN P16_KREDIT END KREDIT, 
					SALDO_BULAN_LALU, DEBET_BI, KREDIT_BI,
					CASE  WHEN SALDO_BULAN_LALU < 0 THEN 'K' WHEN  SALDO_BULAN_LALU > 0 THEN 'D' ELSE ' ' END DK_LALU 
				FROM 
				( SELECT  1 GROUP_SUM, 
					A.COA_ID, (SELECT NM_BUKU_BESAR FROM KBBR_BUKU_BESAR X WHERE A.COA_ID || '.00.00.00' = X.KD_BUKU_BESAR) COA_NAME, KD KD,REPLACE(KD,A.COA_ID||'.')  KD_LEVEL2,NM_BUKU_BESAR
					, P01_DEBET, P02_DEBET, P03_DEBET, P04_DEBET, P05_DEBET, P06_DEBET
					, P07_DEBET, P08_DEBET, P09_DEBET, P10_DEBET, P11_DEBET, P12_DEBET
					,P13_DEBET, P14_DEBET, P15_DEBET, P16_DEBET
					, PSALDO_AWAL
					, P01_KREDIT, P02_KREDIT, P03_KREDIT, P04_KREDIT, P05_KREDIT, P06_KREDIT
					, P07_KREDIT, P08_KREDIT, P09_KREDIT, P10_KREDIT, P11_KREDIT, P12_KREDIT
					,P13_KREDIT, P14_KREDIT, P15_KREDIT, P16_KREDIT, 
					CASE WHEN KD = '606.02.00' THEN AMBIL_LR_THN_JALAN_BL_IMAIS(".$reqBulan.", ".$reqTahun.") ELSE AMBIL_SALDO_AWAL_IKH_BB(KD, ".$reqBulan.", ".$reqTahun.") END SALDO_BULAN_LALU, 
					AMBIL_DEBET_BL_INI_IKH_BB(KD, ".$reqBulan.", ".$reqTahun.") DEBET_BI, AMBIL_KREDIT_BL_INI_IKH_BB(KD, ".$reqBulan.", ".$reqTahun.") KREDIT_BI
				FROM ( 
				SELECT 
					SUBSTR(A.COA_ID,1,(LENGTH(COA_ID)-1)) COA_ID
					,A.KD_BUKU_BESAR KD
					,(SUM(NVL(C.AWAL_DEBET,0)) - SUM(NVL(C.AWAL_KREDIT,0))) PSALDO_AWAL
					,SUM(NVL(C.P01_DEBET,0)) P01_DEBET, SUM(NVL(C.P02_DEBET,0)) P02_DEBET, SUM(NVL(C.P03_DEBET,0)) P03_DEBET
					,SUM(NVL(C.P04_DEBET,0)) P04_DEBET, SUM(NVL(C.P05_DEBET,0)) P05_DEBET, SUM(NVL(C.P06_DEBET,0)) P06_DEBET
					,SUM(NVL(C.P07_DEBET,0)) P07_DEBET, SUM(NVL(C.P08_DEBET,0)) P08_DEBET, SUM(NVL(C.P09_DEBET,0)) P09_DEBET
					,SUM(NVL(C.P10_DEBET,0)) P10_DEBET, SUM(NVL(C.P11_DEBET,0)) P11_DEBET, SUM(NVL(C.P12_DEBET,0)) P12_DEBET 
					,SUM(NVL(C.P13_DEBET,0)) P13_DEBET, SUM(NVL(C.P14_DEBET,0)) P14_DEBET, SUM(NVL(C.P15_DEBET,0)) P15_DEBET
					,SUM(NVL(C.P16_DEBET,0)) P16_DEBET 
					,SUM(NVL(C.P01_KREDIT,0)) P01_KREDIT, SUM(NVL(C.P02_KREDIT,0)) P02_KREDIT, SUM(NVL(C.P03_KREDIT,0)) P03_KREDIT
					,SUM(NVL(C.P04_KREDIT,0)) P04_KREDIT, SUM(NVL(C.P05_KREDIT,0)) P05_KREDIT, SUM(NVL(C.P06_KREDIT,0)) P06_KREDIT
					,SUM(NVL(C.P07_KREDIT,0)) P07_KREDIT, SUM(NVL(C.P08_KREDIT,0)) P08_KREDIT, SUM(NVL(C.P09_KREDIT,0)) P09_KREDIT
					,SUM(NVL(C.P10_KREDIT,0)) P10_KREDIT, SUM(NVL(C.P11_KREDIT,0)) P11_KREDIT, SUM(NVL(C.P12_KREDIT,0)) P12_KREDIT
					,SUM(NVL(C.P13_KREDIT,0)) P13_KREDIT, SUM(NVL(C.P14_KREDIT,0)) P14_KREDIT, SUM(NVL(C.P15_KREDIT,0)) P15_KREDIT
					,SUM(NVL(C.P16_KREDIT,0)) P16_KREDIT
				FROM KBBR_BUKU_BESAR A
				,KBBT_NERACA_SALDO C
				WHERE 
				A.KD_BUKU_BESAR = C.KD_BUKU_BESAR 
                AND C.KD_VALUTA='IDR' 
                AND C.THN_BUKU = ".$reqTahun."
                GROUP BY A.KD_BUKU_BESAR, A.COA_ID
                UNION ALL
                SELECT '606', '606.02.00',
					(SUM(NVL(C.AWAL_DEBET,0)) - SUM(NVL(C.AWAL_KREDIT,0))) PSALDO_AWAL
					,SUM(NVL(C.P01_DEBET,0)) P01_DEBET, SUM(NVL(C.P02_DEBET,0)) P02_DEBET, SUM(NVL(C.P03_DEBET,0)) P03_DEBET
					,SUM(NVL(C.P04_DEBET,0)) P04_DEBET, SUM(NVL(C.P05_DEBET,0)) P05_DEBET, SUM(NVL(C.P06_DEBET,0)) P06_DEBET
					,SUM(NVL(C.P07_DEBET,0)) P07_DEBET, SUM(NVL(C.P08_DEBET,0)) P08_DEBET, SUM(NVL(C.P09_DEBET,0)) P09_DEBET
					,SUM(NVL(C.P10_DEBET,0)) P10_DEBET, SUM(NVL(C.P11_DEBET,0)) P11_DEBET, SUM(NVL(C.P12_DEBET,0)) P12_DEBET 
					,SUM(NVL(C.P13_DEBET,0)) P13_DEBET, SUM(NVL(C.P14_DEBET,0)) P14_DEBET, SUM(NVL(C.P15_DEBET,0)) P15_DEBET
					,SUM(NVL(C.P16_DEBET,0)) P16_DEBET 
					,SUM(NVL(C.P01_KREDIT,0)) P01_KREDIT, SUM(NVL(C.P02_KREDIT,0)) P02_KREDIT, SUM(NVL(C.P03_KREDIT,0)) P03_KREDIT
					,SUM(NVL(C.P04_KREDIT,0)) P04_KREDIT, SUM(NVL(C.P05_KREDIT,0)) P05_KREDIT, SUM(NVL(C.P06_KREDIT,0)) P06_KREDIT
					,SUM(NVL(C.P07_KREDIT,0)) P07_KREDIT, SUM(NVL(C.P08_KREDIT,0)) P08_KREDIT, SUM(NVL(C.P09_KREDIT,0)) P09_KREDIT
					,SUM(NVL(C.P10_KREDIT,0)) P10_KREDIT, SUM(NVL(C.P11_KREDIT,0)) P11_KREDIT, SUM(NVL(C.P12_KREDIT,0)) P12_KREDIT
					,SUM(NVL(C.P13_KREDIT,0)) P13_KREDIT, SUM(NVL(C.P14_KREDIT,0)) P14_KREDIT, SUM(NVL(C.P15_KREDIT,0)) P15_KREDIT
					,SUM(NVL(C.P16_KREDIT,0)) P16_KREDIT
                FROM KBBT_NERACA_SALDO c, KBBR_BUKU_BESAR b
                WHERE 
                                c.thn_buku      = ".$reqTahun."
                                AND    c.kd_buku_besar = b.kd_buku_besar
                                AND    c.kd_valuta     = 'IDR'
                                AND    NVL(SUBSTR(c.kd_buku_besar,1,1),0) >= 7  
                ) A,
                KBBR_BUKU_BESAR B
                WHERE  A.KD = B.KD_BUKU_BESAR
                ORDER BY 1,2,3)))
                WHERE 1=1 
                AND (NOT SALDO_BULAN_INI = 0 or NOT DEBET_BI = 0 or NOT KREDIT_BI = 0)
				"; 
		//, FOTO
		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$order;
		$this->query = $str;
		return $this->selectLimit($str,$limit,$from); 
    }
		
	function selectByParamsBukuBantuV2($paramsArray=array(),$limit=-1,$from=-1, $statement="", $reqBulan="", $reqTahun="", $order="")
	{
		$str = "
		SELECT COA_ID, BUKU_BESAR, KD, NM_BUKU_BESAR, DK_LALU,SALDO_BULAN_LALU, 
                DEBET, KREDIT,  DK_INI, SALDO_BULAN_INI, 
                DEBET_BI, KREDIT_BI, KD_KARTU, NM_KARTU  
		FROM
		(

			SELECT COA_ID, BUKU_BESAR, KD, NM_BUKU_BESAR, DK_LALU,SALDO_BULAN_LALU, 
							DEBET, KREDIT,  DK_INI, SALDO_BULAN_INI, 
							DEBET_BI, KREDIT_BI, KD_KARTU, NM_KARTU  
					FROM
					( 
					SELECT COA_ID, BUKU_BESAR, KD, NM_BUKU_BESAR, DK_LALU, CASE WHEN SALDO_BULAN_LALU < 0 THEN ABS(SALDO_BULAN_LALU) ELSE SALDO_BULAN_LALU END SALDO_BULAN_LALU, 
							DEBET, KREDIT,   
							CASE  WHEN SALDO_BULAN_LALU+DEBET-KREDIT < 0 THEN 'K' WHEN  SALDO_BULAN_LALU+DEBET-KREDIT > 0 THEN 'D' ELSE ' ' END DK_INI,
							CASE WHEN SALDO_BULAN_LALU+DEBET-KREDIT < 0 THEN ABS(SALDO_BULAN_LALU+DEBET-KREDIT) ELSE SALDO_BULAN_LALU+DEBET-KREDIT END SALDO_BULAN_INI, 
							DEBET_BI, KREDIT_BI, KD_KARTU, NM_KARTU 
							FROM (SELECT COA_ID, KD ||' - ' || NM_BUKU_BESAR BUKU_BESAR, KD, NM_BUKU_BESAR, CASE 2 WHEN 01 THEN P01_DEBET  WHEN 02 THEN P02_DEBET WHEN 03 THEN P03_DEBET WHEN 04 THEN P04_DEBET WHEN 05 THEN P05_DEBET 
							WHEN 06 THEN P06_DEBET WHEN 07 THEN P07_DEBET WHEN 08 THEN P08_DEBET  WHEN 09 THEN P09_DEBET WHEN 10 THEN P10_DEBET WHEN 11 THEN P11_DEBET WHEN 12 THEN P12_DEBET WHEN 13 THEN P13_DEBET 
							WHEN 14 THEN P14_DEBET WHEN 15 THEN P15_DEBET WHEN 16 THEN P16_DEBET END DEBET, CASE 2 WHEN 01 THEN P01_KREDIT  WHEN 02 THEN P02_KREDIT WHEN 03 THEN P03_KREDIT WHEN 04 THEN P04_KREDIT WHEN 05 THEN P05_KREDIT 
							WHEN 06 THEN P06_KREDIT WHEN 07 THEN P07_KREDIT WHEN 08 THEN P08_KREDIT  WHEN 09 THEN P09_KREDIT WHEN 10 THEN P10_KREDIT WHEN 11 THEN P11_KREDIT WHEN 12 THEN P12_KREDIT WHEN 13 THEN P13_KREDIT 
							WHEN 14 THEN P14_KREDIT WHEN 15 THEN P15_KREDIT WHEN 16 THEN P16_KREDIT END KREDIT, SALDO_BULAN_LALU, DEBET_BI, KREDIT_BI,
							CASE  WHEN SALDO_BULAN_LALU < 0 THEN 'K' WHEN  SALDO_BULAN_LALU > 0 THEN 'D' ELSE ' ' END DK_LALU, KD_KARTU, NM_KARTU
							FROM (SELECT  A.COA_ID, KD KD, UPPER(NM_BUKU_BESAR) NM_BUKU_BESAR
						   , P01_DEBET, P02_DEBET, P03_DEBET, P04_DEBET, P05_DEBET, P06_DEBET
						   , P07_DEBET, P08_DEBET, P09_DEBET, P10_DEBET, P11_DEBET, P12_DEBET
									   , P13_DEBET, P14_DEBET, P15_DEBET, P16_DEBET
										,PSALDO_AWAL
						   , P01_KREDIT, P02_KREDIT, P03_KREDIT, P04_KREDIT, P05_KREDIT, P06_KREDIT
						   , P07_KREDIT, P08_KREDIT, P09_KREDIT, P10_KREDIT, P11_KREDIT, P12_KREDIT, P13_KREDIT, P14_KREDIT, P15_KREDIT, P16_KREDIT, KD_KARTU, NM_KARTU,
						   SALDO_BULAN_LALU, DEBET_BI, KREDIT_BI
					FROM ( 
							SELECT 
							  SUBSTR(A.KD_BUKU_BESAR,1,3) COA_ID
						   ,A.KD_BUKU_BESAR KD, C.KD_SUB_BANTU KD_KARTU, 
										D.NM_SUB_BANTU NM_KARTU
									   ,(SUM(NVL(C.AWAL_DEBET,0)) - SUM(NVL(C.AWAL_KREDIT,0))) PSALDO_AWAL
						   ,SUM(NVL(C.P01_DEBET,0)) P01_DEBET, SUM(NVL(C.P02_DEBET,0)) P02_DEBET, SUM(NVL(C.P03_DEBET,0)) P03_DEBET
						   ,SUM(NVL(C.P04_DEBET,0)) P04_DEBET, SUM(NVL(C.P05_DEBET,0)) P05_DEBET, SUM(NVL(C.P06_DEBET,0)) P06_DEBET
						   ,SUM(NVL(C.P07_DEBET,0)) P07_DEBET, SUM(NVL(C.P08_DEBET,0)) P08_DEBET, SUM(NVL(C.P09_DEBET,0)) P09_DEBET
						   ,SUM(NVL(C.P10_DEBET,0)) P10_DEBET, SUM(NVL(C.P11_DEBET,0)) P11_DEBET, SUM(NVL(C.P12_DEBET,0)) P12_DEBET 
						   ,SUM(NVL(C.P13_DEBET,0)) P13_DEBET, SUM(NVL(C.P14_DEBET,0)) P14_DEBET, SUM(NVL(C.P15_DEBET,0)) P15_DEBET
						   ,SUM(NVL(C.P16_DEBET,0)) P16_DEBET
						   ,SUM(NVL(C.P01_KREDIT,0)) P01_KREDIT, SUM(NVL(C.P02_KREDIT,0)) P02_KREDIT, SUM(NVL(C.P03_KREDIT,0)) P03_KREDIT
						   ,SUM(NVL(C.P04_KREDIT,0)) P04_KREDIT, SUM(NVL(C.P05_KREDIT,0)) P05_KREDIT, SUM(NVL(C.P06_KREDIT,0)) P06_KREDIT
						   ,SUM(NVL(C.P07_KREDIT,0)) P07_KREDIT, SUM(NVL(C.P08_KREDIT,0)) P08_KREDIT, SUM(NVL(C.P09_KREDIT,0)) P09_KREDIT
						   ,SUM(NVL(C.P10_KREDIT,0)) P10_KREDIT, SUM(NVL(C.P11_KREDIT,0)) P11_KREDIT, SUM(NVL(C.P12_KREDIT,0)) P12_KREDIT
						   ,SUM(NVL(C.P13_KREDIT,0)) P13_KREDIT, SUM(NVL(C.P14_KREDIT,0)) P14_KREDIT, SUM(NVL(C.P15_KREDIT,0)) P15_KREDIT
						   ,SUM(NVL(C.P16_KREDIT,0)) P16_KREDIT
						   FROM KBBR_BUKU_BESAR A
								,KBBT_NERACA_SALDO C
								,KBBR_KARTU_TAMBAH_TEMP D
						   WHERE  A.KD_BUKU_BESAR = C.KD_BUKU_BESAR 
						   AND C.KD_SUB_BANTU <> '00000'
						   AND C.KD_SUB_BANTU = D.KD_SUB_BANTU (+)
							  AND SUBSTR(A.KD_BUKU_BESAR,1,6) NOT IN  ('101.01')
						   AND C.KD_VALUTA='IDR'
						   AND C.THN_BUKU = ".$reqTahun."
						   GROUP BY A.KD_BUKU_BESAR, A.COA_ID, C.KD_SUB_BANTU, D.NM_SUB_BANTU 
						   ) A INNER JOIN
					KBBR_BUKU_BESAR B ON A.KD = B.KD_BUKU_BESAR 
					LEFT JOIN (SELECT KD_BUKU_BESAR, KD_SUB_BANTU, THN_BUKU, nvl(DECODE(".$reqBulan.",1,SUM(NVL(B.P01_DEBET,0))
										,2,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0))
									   ,3,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0))
									   ,4,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0))
									   ,5,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0))
									   ,6,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0))
									   ,7,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0))
									   ,8,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0))
									   ,9,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0)+NVL(B.P09_DEBET,0))
									   ,10,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0)+NVL(B.P09_DEBET,0)+NVL(B.P10_DEBET,0))
									   ,11,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0)+NVL(B.P09_DEBET,0)+NVL(B.P10_DEBET,0)
											  +NVL(B.P11_DEBET,0))
									   ,12,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0)+NVL(B.P09_DEBET,0)+NVL(B.P10_DEBET,0)
											  +NVL(B.P11_DEBET,0)+NVL(B.P12_DEBET,0)) 
									   ,13,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0)+NVL(B.P09_DEBET,0)+NVL(B.P10_DEBET,0)
											  +NVL(B.P11_DEBET,0)+NVL(B.P12_DEBET,0)+NVL(B.P13_DEBET,0)) 
									   ,14,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0)+NVL(B.P09_DEBET,0)+NVL(B.P10_DEBET,0)
											  +NVL(B.P11_DEBET,0)+NVL(B.P12_DEBET,0)+NVL(B.P13_DEBET,0)+NVL(B.P14_DEBET,0))
									   ,15,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0)+NVL(B.P09_DEBET,0)+NVL(B.P10_DEBET,0)
											  +NVL(B.P11_DEBET,0)+NVL(B.P12_DEBET,0)+NVL(B.P13_DEBET,0)+NVL(B.P14_DEBET,0)+NVL(B.P15_DEBET,0)),0),0) DEBET_BI 
									   FROM KBBT_NERACA_SALDO B
									   WHERE KD_VALUTA='IDR'  AND THN_BUKU = ".$reqTahun."
									   GROUP BY KD_BUKU_BESAR, KD_SUB_BANTU, THN_BUKU) C ON A.KD = C.KD_BUKU_BESAR AND A.KD_KARTU = C.KD_SUB_BANTU
						LEFT JOIN (SELECT KD_BUKU_BESAR, KD_SUB_BANTU, THN_BUKU, nvl(DECODE(".$reqBulan.",1,SUM(NVL(B.P01_KREDIT,0))
									,2,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0))
								   ,3,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0))
								   ,4,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0))
								   ,5,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0))
								   ,6,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0))
								   ,7,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0))
								   ,8,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0))
								   ,9,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0)+NVL(B.P09_KREDIT,0))
								   ,10,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0)+NVL(B.P09_KREDIT,0)+NVL(B.P10_KREDIT,0))
								   ,11,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0)+NVL(B.P09_KREDIT,0)+NVL(B.P10_KREDIT,0)
										  +NVL(B.P11_KREDIT,0))
								   ,12,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0)+NVL(B.P09_KREDIT,0)+NVL(B.P10_KREDIT,0)
										  +NVL(B.P11_KREDIT,0)+NVL(B.P12_KREDIT,0))
								   ,13,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0)+NVL(B.P09_KREDIT,0)+NVL(B.P10_KREDIT,0)
										  +NVL(B.P11_KREDIT,0)+NVL(B.P12_KREDIT,0)+NVL(B.P13_KREDIT,0))
								   ,14,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0)+NVL(B.P09_KREDIT,0)+NVL(B.P10_KREDIT,0)
										  +NVL(B.P11_KREDIT,0)+NVL(B.P12_KREDIT,0)+NVL(B.P13_KREDIT,0)+NVL(B.P14_KREDIT,0))
								   ,15,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0)+NVL(B.P09_KREDIT,0)+NVL(B.P10_KREDIT,0)
										  +NVL(B.P11_KREDIT,0)+NVL(B.P12_KREDIT,0)+NVL(B.P13_KREDIT,0)+NVL(B.P14_KREDIT,0)+NVL(B.P15_KREDIT,0)),0),0) KREDIT_BI
									   FROM KBBT_NERACA_SALDO B
									   WHERE KD_VALUTA='IDR'  AND THN_BUKU = ".$reqTahun."
									   GROUP BY KD_BUKU_BESAR, KD_SUB_BANTU, THN_BUKU) D ON A.KD = D.KD_BUKU_BESAR AND A.KD_KARTU = D.KD_SUB_BANTU
							LEFT JOIN (SELECT KD_BUKU_BESAR, KD_SUB_BANTU, THN_BUKU,
										SUM(
										NVL(
										DECODE(".$reqBulan.", 1,
												AWAL_SALDO,
										2,
												AWAL_SALDO + P01_SALDO,
										3,
												AWAL_SALDO + P01_SALDO + P02_SALDO,
										4,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO,
										5,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO,
										6,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO,
										7,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO,
										8,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO,
										9,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO + P08_SALDO,
										10,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO + P08_SALDO + P09_SALDO,
										11,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO + P08_SALDO + P09_SALDO + P10_SALDO,
										12,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO + P08_SALDO + P09_SALDO + P10_SALDO + P11_SALDO,
										13,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO + P08_SALDO + P09_SALDO + P10_SALDO + P11_SALDO + P12_SALDO,
										14,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO + P08_SALDO + P09_SALDO + P10_SALDO + P11_SALDO + P12_SALDO + P13_SALDO,
										15,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO + P08_SALDO + P09_SALDO + P10_SALDO + P11_SALDO + P12_SALDO + P13_SALDO + P14_SALDO), 0)) SALDO_BULAN_LALU 
											   FROM SALDO_AWAL_BANTU_BESAR
											   WHERE THN_BUKU = ".$reqTahun."
											   GROUP BY KD_BUKU_BESAR, KD_SUB_BANTU, THN_BUKU)  E ON A.KD = E.KD_BUKU_BESAR AND A.KD_KARTU = E.KD_SUB_BANTU  
					WHERE NOT A.COA_ID = 101
					ORDER BY KD)) A
					)
					WHERE 1=1 
		
		)
		WHERE 1=1 
		AND (NOT SALDO_BULAN_INI = 0 or NOT DEBET_BI = 0 or NOT KREDIT_BI = 0)
				"; 
		//, FOTO
		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$order;
		$this->query = $str;
		return $this->selectLimit($str,$limit,$from); 
    }
    
	function selectByParamsBukuBantu($paramsArray=array(),$limit=-1,$from=-1, $statement="", $reqBulan="", $reqTahun="", $order="")
	{
		$str = "
		SELECT COA_ID, BUKU_BESAR, KD, NM_BUKU_BESAR, DK_LALU,SALDO_BULAN_LALU, 
                DEBET, KREDIT,  DK_INI, SALDO_BULAN_INI, 
                DEBET_BI, KREDIT_BI, KD_KARTU, NM_KARTU  
		FROM
		( SELECT COA_ID, BUKU_BESAR, KD, NM_BUKU_BESAR, DK_LALU, CASE WHEN SALDO_BULAN_LALU < 0 THEN ABS(SALDO_BULAN_LALU) ELSE SALDO_BULAN_LALU END SALDO_BULAN_LALU, 
				DEBET, KREDIT,   
				CASE  WHEN SALDO_BULAN_LALU+DEBET-KREDIT < 0 THEN 'K' WHEN  SALDO_BULAN_LALU+DEBET-KREDIT > 0 THEN 'D' ELSE ' ' END DK_INI,
				CASE WHEN SALDO_BULAN_LALU+DEBET-KREDIT < 0 THEN ABS(SALDO_BULAN_LALU+DEBET-KREDIT) ELSE SALDO_BULAN_LALU+DEBET-KREDIT END SALDO_BULAN_INI, 
				DEBET_BI, KREDIT_BI, KD_KARTU, NM_KARTU 
				FROM (SELECT COA_ID, KD ||' - ' || NM_BUKU_BESAR BUKU_BESAR, KD, NM_BUKU_BESAR, CASE ".$reqBulan." WHEN 01 THEN P01_DEBET  WHEN 02 THEN P02_DEBET WHEN 03 THEN P03_DEBET WHEN 04 THEN P04_DEBET WHEN 05 THEN P05_DEBET 
				WHEN 06 THEN P06_DEBET WHEN 07 THEN P07_DEBET WHEN 08 THEN P08_DEBET  WHEN 09 THEN P09_DEBET WHEN 10 THEN P10_DEBET WHEN 11 THEN P11_DEBET WHEN 12 THEN P12_DEBET WHEN 13 THEN P13_DEBET 
				WHEN 14 THEN P14_DEBET WHEN 15 THEN P15_DEBET WHEN 16 THEN P16_DEBET END DEBET, CASE ".$reqBulan." WHEN 01 THEN P01_KREDIT  WHEN 02 THEN P02_KREDIT WHEN 03 THEN P03_KREDIT WHEN 04 THEN P04_KREDIT WHEN 05 THEN P05_KREDIT 
				WHEN 06 THEN P06_KREDIT WHEN 07 THEN P07_KREDIT WHEN 08 THEN P08_KREDIT  WHEN 09 THEN P09_KREDIT WHEN 10 THEN P10_KREDIT WHEN 11 THEN P11_KREDIT WHEN 12 THEN P12_KREDIT WHEN 13 THEN P13_KREDIT 
				WHEN 14 THEN P14_KREDIT WHEN 15 THEN P15_KREDIT WHEN 16 THEN P16_KREDIT END KREDIT, SALDO_BULAN_LALU, DEBET_BI, KREDIT_BI,
				CASE  WHEN SALDO_BULAN_LALU < 0 THEN 'K' WHEN  SALDO_BULAN_LALU > 0 THEN 'D' ELSE ' ' END DK_LALU, KD_KARTU, NM_KARTU
				FROM (SELECT  A.COA_ID, KD KD, UPPER(NM_BUKU_BESAR) NM_BUKU_BESAR
			   , P01_DEBET, P02_DEBET, P03_DEBET, P04_DEBET, P05_DEBET, P06_DEBET
			   , P07_DEBET, P08_DEBET, P09_DEBET, P10_DEBET, P11_DEBET, P12_DEBET
						   , P13_DEBET, P14_DEBET, P15_DEBET, P16_DEBET
							,PSALDO_AWAL
			   , P01_KREDIT, P02_KREDIT, P03_KREDIT, P04_KREDIT, P05_KREDIT, P06_KREDIT
			   , P07_KREDIT, P08_KREDIT, P09_KREDIT, P10_KREDIT, P11_KREDIT, P12_KREDIT, P13_KREDIT, P14_KREDIT, P15_KREDIT, P16_KREDIT, KD_KARTU, NM_KARTU
			   , AMBIL_SALDO_AWAL_IKH_BBANTU(KD, KD_KARTU, ".$reqBulan.", ".$reqTahun.") SALDO_BULAN_LALU, 
			   AMBIL_DEBET_BL_INI_IKH_BBANTU(KD, KD_KARTU, ".$reqBulan.", ".$reqTahun.") DEBET_BI, 
			   AMBIL_KREDIT_BL_INI_IKH_BBANTU(KD, KD_KARTU, ".$reqBulan.", ".$reqTahun.") KREDIT_BI
		FROM ( 
				SELECT 
				  SUBSTR(A.KD_BUKU_BESAR,1,3) COA_ID
			   ,A.KD_BUKU_BESAR KD, C.KD_SUB_BANTU KD_KARTU, 
							D.NM_SUB_BANTU NM_KARTU
						   ,(SUM(NVL(C.AWAL_DEBET,0)) - SUM(NVL(C.AWAL_KREDIT,0))) PSALDO_AWAL
			   ,SUM(NVL(C.P01_DEBET,0)) P01_DEBET, SUM(NVL(C.P02_DEBET,0)) P02_DEBET, SUM(NVL(C.P03_DEBET,0)) P03_DEBET
			   ,SUM(NVL(C.P04_DEBET,0)) P04_DEBET, SUM(NVL(C.P05_DEBET,0)) P05_DEBET, SUM(NVL(C.P06_DEBET,0)) P06_DEBET
			   ,SUM(NVL(C.P07_DEBET,0)) P07_DEBET, SUM(NVL(C.P08_DEBET,0)) P08_DEBET, SUM(NVL(C.P09_DEBET,0)) P09_DEBET
			   ,SUM(NVL(C.P10_DEBET,0)) P10_DEBET, SUM(NVL(C.P11_DEBET,0)) P11_DEBET, SUM(NVL(C.P12_DEBET,0)) P12_DEBET 
			   ,SUM(NVL(C.P13_DEBET,0)) P13_DEBET, SUM(NVL(C.P14_DEBET,0)) P14_DEBET, SUM(NVL(C.P15_DEBET,0)) P15_DEBET
			   ,SUM(NVL(C.P16_DEBET,0)) P16_DEBET
			   ,SUM(NVL(C.P01_KREDIT,0)) P01_KREDIT, SUM(NVL(C.P02_KREDIT,0)) P02_KREDIT, SUM(NVL(C.P03_KREDIT,0)) P03_KREDIT
			   ,SUM(NVL(C.P04_KREDIT,0)) P04_KREDIT, SUM(NVL(C.P05_KREDIT,0)) P05_KREDIT, SUM(NVL(C.P06_KREDIT,0)) P06_KREDIT
			   ,SUM(NVL(C.P07_KREDIT,0)) P07_KREDIT, SUM(NVL(C.P08_KREDIT,0)) P08_KREDIT, SUM(NVL(C.P09_KREDIT,0)) P09_KREDIT
			   ,SUM(NVL(C.P10_KREDIT,0)) P10_KREDIT, SUM(NVL(C.P11_KREDIT,0)) P11_KREDIT, SUM(NVL(C.P12_KREDIT,0)) P12_KREDIT
			   ,SUM(NVL(C.P13_KREDIT,0)) P13_KREDIT, SUM(NVL(C.P14_KREDIT,0)) P14_KREDIT, SUM(NVL(C.P15_KREDIT,0)) P15_KREDIT
			   ,SUM(NVL(C.P16_KREDIT,0)) P16_KREDIT
			   FROM KBBR_BUKU_BESAR A
					,KBBT_NERACA_SALDO C
					,KBBR_KARTU_TAMBAH D
			   WHERE  A.KD_BUKU_BESAR = C.KD_BUKU_BESAR 
			   AND C.KD_SUB_BANTU <> '00000'
			   AND C.KD_SUB_BANTU = D.KD_SUB_BANTU (+)
			   AND SUBSTR(A.KD_BUKU_BESAR,1,3) NOT BETWEEN '701' AND '711'
				  AND SUBSTR(A.KD_BUKU_BESAR,1,6) NOT IN  ('101.02')
			   AND SUBSTR(A.KD_BUKU_BESAR,1,3) NOT IN  ('791' ,'606','751','809')
			   AND C.KD_VALUTA='IDR'
			   AND C.THN_BUKU = ".$reqTahun."
			   GROUP BY A.KD_BUKU_BESAR, A.COA_ID, C.KD_SUB_BANTU, D.NM_SUB_BANTU 
			   ) A,
		KBBR_BUKU_BESAR B
		WHERE  A.KD = B.KD_BUKU_BESAR AND NOT A.COA_ID = 101
		ORDER BY KD)))
		WHERE 1=1 
		AND (NOT SALDO_BULAN_INI = 0 or NOT DEBET_BI = 0 or NOT KREDIT_BI = 0)
		AND NM_BUKU_BESAR IN ('BUMN', 'PERUSAHAAN SWASTA', 'Perorangan', 'ABRI', 'Instansi Pemerintah') 
				"; 
		//, FOTO
		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$order;
		$this->query = $str;
		return $this->selectLimit($str,$limit,$from); 
    }
    
	function selectByParamsLike($paramsArray=array(),$limit=-1,$from=-1, $statement="")
	{
		$str = "
				SELECT KD_CABANG, KD_BUKU_BESAR, NM_BUKU_BESAR, 
				TIPE_REKENING, POLA_ENTRY, GRUP_DTL_KODE, 
				GRUP_LEVEL1, GRUP_LEVEL2, GRUP_LEVEL3, 
				GRUP_LEVEL4, GRUP_LEVEL5, KD_BUKU_PUSAT, 
				KD_POSTING_BB, KD_POSTING_SUB, KODE_VALUTA, 
				COA_ID, KET_TAMBAHAN, KD_AKTIF, 
				LAST_UPDATE_DATE, LAST_UPDATED_BY, PROGRAM_NAME
				FROM KBBR_BUKU_BESAR
				WHERE 1 = 1
			    "; 
		
		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key LIKE '%$val%' ";
		}
		
		$this->query = $str;
		$str .= $statement." ORDER BY KD_CABANG ASC";
		return $this->selectLimit($str,$limit,$from); 
    }	
    /** 
    * Hitung jumlah record berdasarkan parameter (array). 
    * @param array paramsArray Array of parameter. Contoh array("id"=>"xxx","IJIN_USAHA_ID"=>"yyy") 
    * @return long Jumlah record yang sesuai kriteria 
    **/ 
    function getCountByParams($paramsArray=array(), $statement="")
	{
		$str = "SELECT COUNT(KD_BUKU_BESAR) AS ROWCOUNT FROM KBBR_BUKU_BESAR
		        WHERE KD_BUKU_BESAR IS NOT NULL ".$statement; 
		
		while(list($key,$val)=each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		$this->select($str);
		$this->query = $str; 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0; 
    }
	
	function getCountByParamsBukuBesar($paramsArray=array(), $statement="", $reqBulan="", $reqTahun="")
	{
		$str = "SELECT COUNT(NM_BUKU_BESAR) AS ROWCOUNT 
				FROM 
				( SELECT COA, KD_LEVEL2, NM_BUKU_BESAR, DK_LALU, CASE WHEN SALDO_BULAN_LALU < 0 THEN ABS(SALDO_BULAN_LALU) ELSE SALDO_BULAN_LALU END SALDO_BULAN_LALU, 
					DEBET, KREDIT, CASE  WHEN SALDO_BULAN_LALU+DEBET-KREDIT < 0 THEN 'K' WHEN  SALDO_BULAN_LALU+DEBET-KREDIT > 0 THEN 'D' ELSE ' ' END DK_INI,
					CASE WHEN SALDO_BULAN_LALU+DEBET-KREDIT < 0 THEN ABS(SALDO_BULAN_LALU+DEBET-KREDIT) ELSE SALDO_BULAN_LALU+DEBET-KREDIT END SALDO_BULAN_INI, 
					DEBET_BI, KREDIT_BI 
				FROM 
				( SELECT COA_ID ||' - ' ||COA_NAME COA, KD_LEVEL2, NM_BUKU_BESAR, 
					CASE ".$reqBulan." WHEN 01 THEN P01_DEBET  WHEN 02 THEN P02_DEBET WHEN 03 THEN P03_DEBET WHEN 04 THEN P04_DEBET WHEN 05 THEN P05_DEBET 
					WHEN 06 THEN P06_DEBET WHEN 07 THEN P07_DEBET WHEN 08 THEN P08_DEBET  WHEN 09 THEN P09_DEBET WHEN 10 THEN P10_DEBET WHEN 11 THEN P11_DEBET 
					WHEN 12 THEN P12_DEBET WHEN 13 THEN P13_DEBET WHEN 14 THEN P14_DEBET WHEN 15 THEN P15_DEBET WHEN 16 THEN P16_DEBET END DEBET, 
					CASE ".$reqBulan." WHEN 01 THEN P01_KREDIT  WHEN 02 THEN P02_KREDIT WHEN 03 THEN P03_KREDIT WHEN 04 THEN P04_KREDIT WHEN 05 THEN P05_KREDIT 
					WHEN 06 THEN P06_KREDIT WHEN 07 THEN P07_KREDIT WHEN 08 THEN P08_KREDIT  WHEN 09 THEN P09_KREDIT WHEN 10 THEN P10_KREDIT WHEN 11 THEN P11_KREDIT 
					WHEN 12 THEN P12_KREDIT WHEN 13 THEN P13_KREDIT WHEN 14 THEN P14_KREDIT WHEN 15 THEN P15_KREDIT WHEN 16 THEN P16_KREDIT END KREDIT, 
					SALDO_BULAN_LALU, DEBET_BI, KREDIT_BI,
					CASE  WHEN SALDO_BULAN_LALU < 0 THEN 'K' WHEN  SALDO_BULAN_LALU > 0 THEN 'D' ELSE ' ' END DK_LALU 
				FROM 
				( SELECT  1 GROUP_SUM, 
					A.COA_ID, (SELECT NM_BUKU_BESAR FROM KBBR_BUKU_BESAR X WHERE A.COA_ID || '.00.00.00' = X.KD_BUKU_BESAR) COA_NAME, KD KD,REPLACE(KD,A.COA_ID||'.')  KD_LEVEL2,NM_BUKU_BESAR
					, P01_DEBET, P02_DEBET, P03_DEBET, P04_DEBET, P05_DEBET, P06_DEBET
					, P07_DEBET, P08_DEBET, P09_DEBET, P10_DEBET, P11_DEBET, P12_DEBET
					,P13_DEBET, P14_DEBET, P15_DEBET, P16_DEBET
					, PSALDO_AWAL
					, P01_KREDIT, P02_KREDIT, P03_KREDIT, P04_KREDIT, P05_KREDIT, P06_KREDIT
					, P07_KREDIT, P08_KREDIT, P09_KREDIT, P10_KREDIT, P11_KREDIT, P12_KREDIT
					,P13_KREDIT, P14_KREDIT, P15_KREDIT, P16_KREDIT, 
					CASE WHEN KD = '606.02.00' THEN AMBIL_LR_THN_JALAN_BL_IMAIS(".$reqBulan.", ".$reqTahun.") ELSE AMBIL_SALDO_AWAL_IKH_BB(KD, ".$reqBulan.", ".$reqTahun.") END SALDO_BULAN_LALU, 
					AMBIL_DEBET_BL_INI_IKH_BB(KD, ".$reqBulan.", ".$reqTahun.") DEBET_BI, AMBIL_KREDIT_BL_INI_IKH_BB(KD, ".$reqBulan.", ".$reqTahun.") KREDIT_BI
				FROM ( 
				SELECT 
					SUBSTR(A.COA_ID,1,(LENGTH(COA_ID)-1)) COA_ID
					,A.KD_BUKU_BESAR KD
					,(SUM(NVL(C.AWAL_DEBET,0)) - SUM(NVL(C.AWAL_KREDIT,0))) PSALDO_AWAL
					,SUM(NVL(C.P01_DEBET,0)) P01_DEBET, SUM(NVL(C.P02_DEBET,0)) P02_DEBET, SUM(NVL(C.P03_DEBET,0)) P03_DEBET
					,SUM(NVL(C.P04_DEBET,0)) P04_DEBET, SUM(NVL(C.P05_DEBET,0)) P05_DEBET, SUM(NVL(C.P06_DEBET,0)) P06_DEBET
					,SUM(NVL(C.P07_DEBET,0)) P07_DEBET, SUM(NVL(C.P08_DEBET,0)) P08_DEBET, SUM(NVL(C.P09_DEBET,0)) P09_DEBET
					,SUM(NVL(C.P10_DEBET,0)) P10_DEBET, SUM(NVL(C.P11_DEBET,0)) P11_DEBET, SUM(NVL(C.P12_DEBET,0)) P12_DEBET 
					,SUM(NVL(C.P13_DEBET,0)) P13_DEBET, SUM(NVL(C.P14_DEBET,0)) P14_DEBET, SUM(NVL(C.P15_DEBET,0)) P15_DEBET
					,SUM(NVL(C.P16_DEBET,0)) P16_DEBET 
					,SUM(NVL(C.P01_KREDIT,0)) P01_KREDIT, SUM(NVL(C.P02_KREDIT,0)) P02_KREDIT, SUM(NVL(C.P03_KREDIT,0)) P03_KREDIT
					,SUM(NVL(C.P04_KREDIT,0)) P04_KREDIT, SUM(NVL(C.P05_KREDIT,0)) P05_KREDIT, SUM(NVL(C.P06_KREDIT,0)) P06_KREDIT
					,SUM(NVL(C.P07_KREDIT,0)) P07_KREDIT, SUM(NVL(C.P08_KREDIT,0)) P08_KREDIT, SUM(NVL(C.P09_KREDIT,0)) P09_KREDIT
					,SUM(NVL(C.P10_KREDIT,0)) P10_KREDIT, SUM(NVL(C.P11_KREDIT,0)) P11_KREDIT, SUM(NVL(C.P12_KREDIT,0)) P12_KREDIT
					,SUM(NVL(C.P13_KREDIT,0)) P13_KREDIT, SUM(NVL(C.P14_KREDIT,0)) P14_KREDIT, SUM(NVL(C.P15_KREDIT,0)) P15_KREDIT
					,SUM(NVL(C.P16_KREDIT,0)) P16_KREDIT
				FROM KBBR_BUKU_BESAR A
				,KBBT_NERACA_SALDO C
				WHERE 
				A.KD_BUKU_BESAR = C.KD_BUKU_BESAR 
                AND C.KD_VALUTA='IDR' 
                AND C.THN_BUKU = ".$reqTahun."
                GROUP BY A.KD_BUKU_BESAR, A.COA_ID
                UNION ALL
                SELECT '606', '606.02.00',
					(SUM(NVL(C.AWAL_DEBET,0)) - SUM(NVL(C.AWAL_KREDIT,0))) PSALDO_AWAL
					,SUM(NVL(C.P01_DEBET,0)) P01_DEBET, SUM(NVL(C.P02_DEBET,0)) P02_DEBET, SUM(NVL(C.P03_DEBET,0)) P03_DEBET
					,SUM(NVL(C.P04_DEBET,0)) P04_DEBET, SUM(NVL(C.P05_DEBET,0)) P05_DEBET, SUM(NVL(C.P06_DEBET,0)) P06_DEBET
					,SUM(NVL(C.P07_DEBET,0)) P07_DEBET, SUM(NVL(C.P08_DEBET,0)) P08_DEBET, SUM(NVL(C.P09_DEBET,0)) P09_DEBET
					,SUM(NVL(C.P10_DEBET,0)) P10_DEBET, SUM(NVL(C.P11_DEBET,0)) P11_DEBET, SUM(NVL(C.P12_DEBET,0)) P12_DEBET 
					,SUM(NVL(C.P13_DEBET,0)) P13_DEBET, SUM(NVL(C.P14_DEBET,0)) P14_DEBET, SUM(NVL(C.P15_DEBET,0)) P15_DEBET
					,SUM(NVL(C.P16_DEBET,0)) P16_DEBET 
					,SUM(NVL(C.P01_KREDIT,0)) P01_KREDIT, SUM(NVL(C.P02_KREDIT,0)) P02_KREDIT, SUM(NVL(C.P03_KREDIT,0)) P03_KREDIT
					,SUM(NVL(C.P04_KREDIT,0)) P04_KREDIT, SUM(NVL(C.P05_KREDIT,0)) P05_KREDIT, SUM(NVL(C.P06_KREDIT,0)) P06_KREDIT
					,SUM(NVL(C.P07_KREDIT,0)) P07_KREDIT, SUM(NVL(C.P08_KREDIT,0)) P08_KREDIT, SUM(NVL(C.P09_KREDIT,0)) P09_KREDIT
					,SUM(NVL(C.P10_KREDIT,0)) P10_KREDIT, SUM(NVL(C.P11_KREDIT,0)) P11_KREDIT, SUM(NVL(C.P12_KREDIT,0)) P12_KREDIT
					,SUM(NVL(C.P13_KREDIT,0)) P13_KREDIT, SUM(NVL(C.P14_KREDIT,0)) P14_KREDIT, SUM(NVL(C.P15_KREDIT,0)) P15_KREDIT
					,SUM(NVL(C.P16_KREDIT,0)) P16_KREDIT
                FROM KBBT_NERACA_SALDO c, KBBR_BUKU_BESAR b
                WHERE 
                                c.thn_buku      = ".$reqTahun."
                                AND    c.kd_buku_besar = b.kd_buku_besar
                                AND    c.kd_valuta     = 'IDR'
                                AND    NVL(SUBSTR(c.kd_buku_besar,1,1),0) >= 7  
                ) A,
                KBBR_BUKU_BESAR B
                WHERE  A.KD = B.KD_BUKU_BESAR
                ORDER BY 1,2,3)))
                WHERE 1=1 
                AND (NOT SALDO_BULAN_INI = 0 or NOT DEBET_BI = 0 or NOT KREDIT_BI = 0) ".$statement; 
		
		while(list($key,$val)=each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		$this->select($str);
		$this->query = $str; 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0; 
    }
	
	
	function getCountByParamsBukuBantuV2($paramsArray=array(), $statement="", $reqBulan="", $reqTahun="")
	{
		$str = "SELECT COUNT(1) AS ROWCOUNT 
		FROM 
		(


SELECT COA_ID, BUKU_BESAR, KD, NM_BUKU_BESAR, DK_LALU,SALDO_BULAN_LALU, 
							DEBET, KREDIT,  DK_INI, SALDO_BULAN_INI, 
							DEBET_BI, KREDIT_BI, KD_KARTU, NM_KARTU  
					FROM
					( 
					SELECT COA_ID, BUKU_BESAR, KD, NM_BUKU_BESAR, DK_LALU, CASE WHEN SALDO_BULAN_LALU < 0 THEN ABS(SALDO_BULAN_LALU) ELSE SALDO_BULAN_LALU END SALDO_BULAN_LALU, 
							DEBET, KREDIT,   
							CASE  WHEN SALDO_BULAN_LALU+DEBET-KREDIT < 0 THEN 'K' WHEN  SALDO_BULAN_LALU+DEBET-KREDIT > 0 THEN 'D' ELSE ' ' END DK_INI,
							CASE WHEN SALDO_BULAN_LALU+DEBET-KREDIT < 0 THEN ABS(SALDO_BULAN_LALU+DEBET-KREDIT) ELSE SALDO_BULAN_LALU+DEBET-KREDIT END SALDO_BULAN_INI, 
							DEBET_BI, KREDIT_BI, KD_KARTU, NM_KARTU 
							FROM (SELECT COA_ID, KD ||' - ' || NM_BUKU_BESAR BUKU_BESAR, KD, NM_BUKU_BESAR, CASE 2 WHEN 01 THEN P01_DEBET  WHEN 02 THEN P02_DEBET WHEN 03 THEN P03_DEBET WHEN 04 THEN P04_DEBET WHEN 05 THEN P05_DEBET 
							WHEN 06 THEN P06_DEBET WHEN 07 THEN P07_DEBET WHEN 08 THEN P08_DEBET  WHEN 09 THEN P09_DEBET WHEN 10 THEN P10_DEBET WHEN 11 THEN P11_DEBET WHEN 12 THEN P12_DEBET WHEN 13 THEN P13_DEBET 
							WHEN 14 THEN P14_DEBET WHEN 15 THEN P15_DEBET WHEN 16 THEN P16_DEBET END DEBET, CASE 2 WHEN 01 THEN P01_KREDIT  WHEN 02 THEN P02_KREDIT WHEN 03 THEN P03_KREDIT WHEN 04 THEN P04_KREDIT WHEN 05 THEN P05_KREDIT 
							WHEN 06 THEN P06_KREDIT WHEN 07 THEN P07_KREDIT WHEN 08 THEN P08_KREDIT  WHEN 09 THEN P09_KREDIT WHEN 10 THEN P10_KREDIT WHEN 11 THEN P11_KREDIT WHEN 12 THEN P12_KREDIT WHEN 13 THEN P13_KREDIT 
							WHEN 14 THEN P14_KREDIT WHEN 15 THEN P15_KREDIT WHEN 16 THEN P16_KREDIT END KREDIT, SALDO_BULAN_LALU, DEBET_BI, KREDIT_BI,
							CASE  WHEN SALDO_BULAN_LALU < 0 THEN 'K' WHEN  SALDO_BULAN_LALU > 0 THEN 'D' ELSE ' ' END DK_LALU, KD_KARTU, NM_KARTU
							FROM (SELECT  A.COA_ID, KD KD, UPPER(NM_BUKU_BESAR) NM_BUKU_BESAR
						   , P01_DEBET, P02_DEBET, P03_DEBET, P04_DEBET, P05_DEBET, P06_DEBET
						   , P07_DEBET, P08_DEBET, P09_DEBET, P10_DEBET, P11_DEBET, P12_DEBET
									   , P13_DEBET, P14_DEBET, P15_DEBET, P16_DEBET
										,PSALDO_AWAL
						   , P01_KREDIT, P02_KREDIT, P03_KREDIT, P04_KREDIT, P05_KREDIT, P06_KREDIT
						   , P07_KREDIT, P08_KREDIT, P09_KREDIT, P10_KREDIT, P11_KREDIT, P12_KREDIT, P13_KREDIT, P14_KREDIT, P15_KREDIT, P16_KREDIT, KD_KARTU, NM_KARTU,
						   SALDO_BULAN_LALU, DEBET_BI, KREDIT_BI
					FROM ( 
							SELECT 
							  SUBSTR(A.KD_BUKU_BESAR,1,3) COA_ID
						   ,A.KD_BUKU_BESAR KD, C.KD_SUB_BANTU KD_KARTU, 
										D.NM_SUB_BANTU NM_KARTU
									   ,(SUM(NVL(C.AWAL_DEBET,0)) - SUM(NVL(C.AWAL_KREDIT,0))) PSALDO_AWAL
						   ,SUM(NVL(C.P01_DEBET,0)) P01_DEBET, SUM(NVL(C.P02_DEBET,0)) P02_DEBET, SUM(NVL(C.P03_DEBET,0)) P03_DEBET
						   ,SUM(NVL(C.P04_DEBET,0)) P04_DEBET, SUM(NVL(C.P05_DEBET,0)) P05_DEBET, SUM(NVL(C.P06_DEBET,0)) P06_DEBET
						   ,SUM(NVL(C.P07_DEBET,0)) P07_DEBET, SUM(NVL(C.P08_DEBET,0)) P08_DEBET, SUM(NVL(C.P09_DEBET,0)) P09_DEBET
						   ,SUM(NVL(C.P10_DEBET,0)) P10_DEBET, SUM(NVL(C.P11_DEBET,0)) P11_DEBET, SUM(NVL(C.P12_DEBET,0)) P12_DEBET 
						   ,SUM(NVL(C.P13_DEBET,0)) P13_DEBET, SUM(NVL(C.P14_DEBET,0)) P14_DEBET, SUM(NVL(C.P15_DEBET,0)) P15_DEBET
						   ,SUM(NVL(C.P16_DEBET,0)) P16_DEBET
						   ,SUM(NVL(C.P01_KREDIT,0)) P01_KREDIT, SUM(NVL(C.P02_KREDIT,0)) P02_KREDIT, SUM(NVL(C.P03_KREDIT,0)) P03_KREDIT
						   ,SUM(NVL(C.P04_KREDIT,0)) P04_KREDIT, SUM(NVL(C.P05_KREDIT,0)) P05_KREDIT, SUM(NVL(C.P06_KREDIT,0)) P06_KREDIT
						   ,SUM(NVL(C.P07_KREDIT,0)) P07_KREDIT, SUM(NVL(C.P08_KREDIT,0)) P08_KREDIT, SUM(NVL(C.P09_KREDIT,0)) P09_KREDIT
						   ,SUM(NVL(C.P10_KREDIT,0)) P10_KREDIT, SUM(NVL(C.P11_KREDIT,0)) P11_KREDIT, SUM(NVL(C.P12_KREDIT,0)) P12_KREDIT
						   ,SUM(NVL(C.P13_KREDIT,0)) P13_KREDIT, SUM(NVL(C.P14_KREDIT,0)) P14_KREDIT, SUM(NVL(C.P15_KREDIT,0)) P15_KREDIT
						   ,SUM(NVL(C.P16_KREDIT,0)) P16_KREDIT
						   FROM KBBR_BUKU_BESAR A
								,KBBT_NERACA_SALDO C
								,KBBR_KARTU_TAMBAH_TEMP D
						   WHERE  A.KD_BUKU_BESAR = C.KD_BUKU_BESAR 
						   AND C.KD_SUB_BANTU <> '00000'
						   AND C.KD_SUB_BANTU = D.KD_SUB_BANTU (+)
							  AND SUBSTR(A.KD_BUKU_BESAR,1,6) NOT IN  ('101.01')
						   AND C.KD_VALUTA='IDR'
						   AND C.THN_BUKU = ".$reqTahun."
						   GROUP BY A.KD_BUKU_BESAR, A.COA_ID, C.KD_SUB_BANTU, D.NM_SUB_BANTU 
						   ) A INNER JOIN
					KBBR_BUKU_BESAR B ON A.KD = B.KD_BUKU_BESAR 
					LEFT JOIN (SELECT KD_BUKU_BESAR, KD_SUB_BANTU, THN_BUKU, nvl(DECODE(".$reqBulan.",1,SUM(NVL(B.P01_DEBET,0))
										,2,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0))
									   ,3,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0))
									   ,4,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0))
									   ,5,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0))
									   ,6,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0))
									   ,7,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0))
									   ,8,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0))
									   ,9,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0)+NVL(B.P09_DEBET,0))
									   ,10,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0)+NVL(B.P09_DEBET,0)+NVL(B.P10_DEBET,0))
									   ,11,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0)+NVL(B.P09_DEBET,0)+NVL(B.P10_DEBET,0)
											  +NVL(B.P11_DEBET,0))
									   ,12,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0)+NVL(B.P09_DEBET,0)+NVL(B.P10_DEBET,0)
											  +NVL(B.P11_DEBET,0)+NVL(B.P12_DEBET,0)) 
									   ,13,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0)+NVL(B.P09_DEBET,0)+NVL(B.P10_DEBET,0)
											  +NVL(B.P11_DEBET,0)+NVL(B.P12_DEBET,0)+NVL(B.P13_DEBET,0)) 
									   ,14,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0)+NVL(B.P09_DEBET,0)+NVL(B.P10_DEBET,0)
											  +NVL(B.P11_DEBET,0)+NVL(B.P12_DEBET,0)+NVL(B.P13_DEBET,0)+NVL(B.P14_DEBET,0))
									   ,15,SUM(NVL(B.P01_DEBET,0)+NVL(B.P02_DEBET,0)+NVL(B.P03_DEBET,0)+NVL(B.P04_DEBET,0)+NVL(B.P05_DEBET,0)
											  +NVL(B.P06_DEBET,0)+NVL(B.P07_DEBET,0)+NVL(B.P08_DEBET,0)+NVL(B.P09_DEBET,0)+NVL(B.P10_DEBET,0)
											  +NVL(B.P11_DEBET,0)+NVL(B.P12_DEBET,0)+NVL(B.P13_DEBET,0)+NVL(B.P14_DEBET,0)+NVL(B.P15_DEBET,0)),0),0) DEBET_BI 
									   FROM KBBT_NERACA_SALDO B
									   WHERE KD_VALUTA='IDR'  AND THN_BUKU = ".$reqTahun."
									   GROUP BY KD_BUKU_BESAR, KD_SUB_BANTU, THN_BUKU) C ON A.KD = C.KD_BUKU_BESAR AND A.KD_KARTU = C.KD_SUB_BANTU
						LEFT JOIN (SELECT KD_BUKU_BESAR, KD_SUB_BANTU, THN_BUKU, nvl(DECODE(".$reqBulan.",1,SUM(NVL(B.P01_KREDIT,0))
									,2,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0))
								   ,3,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0))
								   ,4,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0))
								   ,5,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0))
								   ,6,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0))
								   ,7,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0))
								   ,8,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0))
								   ,9,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0)+NVL(B.P09_KREDIT,0))
								   ,10,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0)+NVL(B.P09_KREDIT,0)+NVL(B.P10_KREDIT,0))
								   ,11,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0)+NVL(B.P09_KREDIT,0)+NVL(B.P10_KREDIT,0)
										  +NVL(B.P11_KREDIT,0))
								   ,12,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0)+NVL(B.P09_KREDIT,0)+NVL(B.P10_KREDIT,0)
										  +NVL(B.P11_KREDIT,0)+NVL(B.P12_KREDIT,0))
								   ,13,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0)+NVL(B.P09_KREDIT,0)+NVL(B.P10_KREDIT,0)
										  +NVL(B.P11_KREDIT,0)+NVL(B.P12_KREDIT,0)+NVL(B.P13_KREDIT,0))
								   ,14,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0)+NVL(B.P09_KREDIT,0)+NVL(B.P10_KREDIT,0)
										  +NVL(B.P11_KREDIT,0)+NVL(B.P12_KREDIT,0)+NVL(B.P13_KREDIT,0)+NVL(B.P14_KREDIT,0))
								   ,15,SUM(NVL(B.P01_KREDIT,0)+NVL(B.P02_KREDIT,0)+NVL(B.P03_KREDIT,0)+NVL(B.P04_KREDIT,0)+NVL(B.P05_KREDIT,0)
										  +NVL(B.P06_KREDIT,0)+NVL(B.P07_KREDIT,0)+NVL(B.P08_KREDIT,0)+NVL(B.P09_KREDIT,0)+NVL(B.P10_KREDIT,0)
										  +NVL(B.P11_KREDIT,0)+NVL(B.P12_KREDIT,0)+NVL(B.P13_KREDIT,0)+NVL(B.P14_KREDIT,0)+NVL(B.P15_KREDIT,0)),0),0) KREDIT_BI
									   FROM KBBT_NERACA_SALDO B
									   WHERE KD_VALUTA='IDR'  AND THN_BUKU = ".$reqTahun."
									   GROUP BY KD_BUKU_BESAR, KD_SUB_BANTU, THN_BUKU) D ON A.KD = D.KD_BUKU_BESAR AND A.KD_KARTU = D.KD_SUB_BANTU
							LEFT JOIN (SELECT KD_BUKU_BESAR, KD_SUB_BANTU, THN_BUKU,
										SUM(
										NVL(
										DECODE(".$reqBulan.", 1,
												AWAL_SALDO,
										2,
												AWAL_SALDO + P01_SALDO,
										3,
												AWAL_SALDO + P01_SALDO + P02_SALDO,
										4,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO,
										5,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO,
										6,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO,
										7,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO,
										8,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO,
										9,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO + P08_SALDO,
										10,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO + P08_SALDO + P09_SALDO,
										11,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO + P08_SALDO + P09_SALDO + P10_SALDO,
										12,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO + P08_SALDO + P09_SALDO + P10_SALDO + P11_SALDO,
										13,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO + P08_SALDO + P09_SALDO + P10_SALDO + P11_SALDO + P12_SALDO,
										14,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO + P08_SALDO + P09_SALDO + P10_SALDO + P11_SALDO + P12_SALDO + P13_SALDO,
										15,
												AWAL_SALDO + P01_SALDO + P02_SALDO + P03_SALDO + P04_SALDO + P05_SALDO + P06_SALDO + P07_SALDO + P08_SALDO + P09_SALDO + P10_SALDO + P11_SALDO + P12_SALDO + P13_SALDO + P14_SALDO), 0)) SALDO_BULAN_LALU 
											   FROM SALDO_AWAL_BANTU_BESAR
											   WHERE THN_BUKU = ".$reqTahun."
											   GROUP BY KD_BUKU_BESAR, KD_SUB_BANTU, THN_BUKU)  E ON A.KD = E.KD_BUKU_BESAR AND A.KD_KARTU = E.KD_SUB_BANTU  
					WHERE NOT A.COA_ID = 101
					ORDER BY KD)) A
					)
					WHERE 1=1 
							
		)
		WHERE 1=1 
		AND (NOT SALDO_BULAN_INI = 0 or NOT DEBET_BI = 0 or NOT KREDIT_BI = 0) ".$statement; 
		
		while(list($key,$val)=each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		$this->select($str);
		$this->query = $str; 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0; 
    }


	
	function getCountByParamsBukuBantu($paramsArray=array(), $statement="", $reqBulan="", $reqTahun="")
	{
		$str = "SELECT COUNT(NM_BUKU_BESAR) AS ROWCOUNT 
		FROM 
		( SELECT COA_ID, BUKU_BESAR, KD, NM_BUKU_BESAR, DK_LALU, CASE WHEN SALDO_BULAN_LALU < 0 THEN ABS(SALDO_BULAN_LALU) ELSE SALDO_BULAN_LALU END SALDO_BULAN_LALU, 
				DEBET, KREDIT,   
				CASE  WHEN SALDO_BULAN_LALU+DEBET-KREDIT < 0 THEN 'K' WHEN  SALDO_BULAN_LALU+DEBET-KREDIT > 0 THEN 'D' ELSE ' ' END DK_INI,
				CASE WHEN SALDO_BULAN_LALU+DEBET-KREDIT < 0 THEN ABS(SALDO_BULAN_LALU+DEBET-KREDIT) ELSE SALDO_BULAN_LALU+DEBET-KREDIT END SALDO_BULAN_INI, 
				DEBET_BI, KREDIT_BI, KD_KARTU, NM_KARTU 
				FROM (SELECT COA_ID, KD ||' - ' || NM_BUKU_BESAR BUKU_BESAR, KD, NM_BUKU_BESAR, CASE ".$reqBulan." WHEN 01 THEN P01_DEBET  WHEN 02 THEN P02_DEBET WHEN 03 THEN P03_DEBET WHEN 04 THEN P04_DEBET WHEN 05 THEN P05_DEBET 
				WHEN 06 THEN P06_DEBET WHEN 07 THEN P07_DEBET WHEN 08 THEN P08_DEBET  WHEN 09 THEN P09_DEBET WHEN 10 THEN P10_DEBET WHEN 11 THEN P11_DEBET WHEN 12 THEN P12_DEBET WHEN 13 THEN P13_DEBET 
				WHEN 14 THEN P14_DEBET WHEN 15 THEN P15_DEBET WHEN 16 THEN P16_DEBET END DEBET, CASE ".$reqBulan." WHEN 01 THEN P01_KREDIT  WHEN 02 THEN P02_KREDIT WHEN 03 THEN P03_KREDIT WHEN 04 THEN P04_KREDIT WHEN 05 THEN P05_KREDIT 
				WHEN 06 THEN P06_KREDIT WHEN 07 THEN P07_KREDIT WHEN 08 THEN P08_KREDIT  WHEN 09 THEN P09_KREDIT WHEN 10 THEN P10_KREDIT WHEN 11 THEN P11_KREDIT WHEN 12 THEN P12_KREDIT WHEN 13 THEN P13_KREDIT 
				WHEN 14 THEN P14_KREDIT WHEN 15 THEN P15_KREDIT WHEN 16 THEN P16_KREDIT END KREDIT, SALDO_BULAN_LALU, DEBET_BI, KREDIT_BI,
				CASE  WHEN SALDO_BULAN_LALU < 0 THEN 'K' WHEN  SALDO_BULAN_LALU > 0 THEN 'D' ELSE ' ' END DK_LALU, KD_KARTU, NM_KARTU
				FROM (SELECT  A.COA_ID, KD KD, UPPER(NM_BUKU_BESAR) NM_BUKU_BESAR
			   , P01_DEBET, P02_DEBET, P03_DEBET, P04_DEBET, P05_DEBET, P06_DEBET
			   , P07_DEBET, P08_DEBET, P09_DEBET, P10_DEBET, P11_DEBET, P12_DEBET
						   , P13_DEBET, P14_DEBET, P15_DEBET, P16_DEBET
							,PSALDO_AWAL
			   , P01_KREDIT, P02_KREDIT, P03_KREDIT, P04_KREDIT, P05_KREDIT, P06_KREDIT
			   , P07_KREDIT, P08_KREDIT, P09_KREDIT, P10_KREDIT, P11_KREDIT, P12_KREDIT, P13_KREDIT, P14_KREDIT, P15_KREDIT, P16_KREDIT, KD_KARTU, NM_KARTU
			   , AMBIL_SALDO_AWAL_IKH_BBANTU(KD, KD_KARTU, ".$reqBulan.", ".$reqTahun.") SALDO_BULAN_LALU, 
			   AMBIL_DEBET_BL_INI_IKH_BBANTU(KD, KD_KARTU, ".$reqBulan.", ".$reqTahun.") DEBET_BI, 
			   AMBIL_KREDIT_BL_INI_IKH_BBANTU(KD, KD_KARTU, ".$reqBulan.", ".$reqTahun.") KREDIT_BI
		FROM ( 
				SELECT 
				  SUBSTR(A.KD_BUKU_BESAR,1,3) COA_ID
			   ,A.KD_BUKU_BESAR KD, C.KD_SUB_BANTU KD_KARTU, 
							D.NM_SUB_BANTU NM_KARTU
						   ,(SUM(NVL(C.AWAL_DEBET,0)) - SUM(NVL(C.AWAL_KREDIT,0))) PSALDO_AWAL
			   ,SUM(NVL(C.P01_DEBET,0)) P01_DEBET, SUM(NVL(C.P02_DEBET,0)) P02_DEBET, SUM(NVL(C.P03_DEBET,0)) P03_DEBET
			   ,SUM(NVL(C.P04_DEBET,0)) P04_DEBET, SUM(NVL(C.P05_DEBET,0)) P05_DEBET, SUM(NVL(C.P06_DEBET,0)) P06_DEBET
			   ,SUM(NVL(C.P07_DEBET,0)) P07_DEBET, SUM(NVL(C.P08_DEBET,0)) P08_DEBET, SUM(NVL(C.P09_DEBET,0)) P09_DEBET
			   ,SUM(NVL(C.P10_DEBET,0)) P10_DEBET, SUM(NVL(C.P11_DEBET,0)) P11_DEBET, SUM(NVL(C.P12_DEBET,0)) P12_DEBET 
			   ,SUM(NVL(C.P13_DEBET,0)) P13_DEBET, SUM(NVL(C.P14_DEBET,0)) P14_DEBET, SUM(NVL(C.P15_DEBET,0)) P15_DEBET
			   ,SUM(NVL(C.P16_DEBET,0)) P16_DEBET
			   ,SUM(NVL(C.P01_KREDIT,0)) P01_KREDIT, SUM(NVL(C.P02_KREDIT,0)) P02_KREDIT, SUM(NVL(C.P03_KREDIT,0)) P03_KREDIT
			   ,SUM(NVL(C.P04_KREDIT,0)) P04_KREDIT, SUM(NVL(C.P05_KREDIT,0)) P05_KREDIT, SUM(NVL(C.P06_KREDIT,0)) P06_KREDIT
			   ,SUM(NVL(C.P07_KREDIT,0)) P07_KREDIT, SUM(NVL(C.P08_KREDIT,0)) P08_KREDIT, SUM(NVL(C.P09_KREDIT,0)) P09_KREDIT
			   ,SUM(NVL(C.P10_KREDIT,0)) P10_KREDIT, SUM(NVL(C.P11_KREDIT,0)) P11_KREDIT, SUM(NVL(C.P12_KREDIT,0)) P12_KREDIT
			   ,SUM(NVL(C.P13_KREDIT,0)) P13_KREDIT, SUM(NVL(C.P14_KREDIT,0)) P14_KREDIT, SUM(NVL(C.P15_KREDIT,0)) P15_KREDIT
			   ,SUM(NVL(C.P16_KREDIT,0)) P16_KREDIT
			   FROM KBBR_BUKU_BESAR A
					,KBBT_NERACA_SALDO C
					,KBBR_KARTU_TAMBAH D
			   WHERE  A.KD_BUKU_BESAR = C.KD_BUKU_BESAR 
			   AND C.KD_SUB_BANTU <> '00000'
			   AND C.KD_SUB_BANTU = D.KD_SUB_BANTU (+)
			   AND SUBSTR(A.KD_BUKU_BESAR,1,3) NOT BETWEEN '701' AND '711'
				  AND SUBSTR(A.KD_BUKU_BESAR,1,6) NOT IN  ('101.02')
			   AND SUBSTR(A.KD_BUKU_BESAR,1,3) NOT IN  ('791' ,'606','751','809')
			   AND C.KD_VALUTA='IDR'
			   AND C.THN_BUKU = ".$reqTahun."
			   GROUP BY A.KD_BUKU_BESAR, A.COA_ID, C.KD_SUB_BANTU, D.NM_SUB_BANTU 
			   ) A,
		KBBR_BUKU_BESAR B
		WHERE  A.KD = B.KD_BUKU_BESAR AND NOT A.COA_ID = 101
		ORDER BY KD)))
		WHERE 1=1 
		AND (NOT SALDO_BULAN_INI = 0 or NOT DEBET_BI = 0 or NOT KREDIT_BI = 0)
		AND NM_BUKU_BESAR IN ('BUMN', 'PERUSAHAAN SWASTA', 'Perorangan', 'ABRI', 'Instansi Pemerintah') ".$statement; 
		
		while(list($key,$val)=each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		echo $str; exit;
		$this->select($str);
		$this->query = $str; 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0; 
    }

    function getCountByParamsLike($paramsArray=array(), $statement="")
	{
		$str = "SELECT COUNT(KD_BUKU_BESAR) AS ROWCOUNT FROM KBBR_BUKU_BESAR
		        WHERE KD_BUKU_BESAR IS NOT NULL ".$statement; 
		while(list($key,$val)=each($paramsArray))
		{
			$str .= " AND $key LIKE '%$val%' ";
		}
		
		$this->select($str); 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0; 
    }	
  } 
?>