<? 
/* *******************************************************************************************************
MODUL NAME 			: MTSN LAWANG
FILE NAME 			: 
AUTHOR				: 
VERSION				: 1.0
MODIFICATION DOC	:
DESCRIPTION			: 
***************************************************************************************************** */

  /***
  * Entity-base class untuk mengimplementasikan tabel kategori.
  * 
  ***/
  include_once("../WEB-INF/classes/db/Entity.php");

  class Integrasi extends Entity{ 

	var $query;
    /**
    * Class constructor.
    **/
    function Integrasi()
	{
      $this->Entity(); 
    }
	
    function selectByParamsAgama($statement="")
	{
		$str = "
				SELECT A.AGAMA_ID, NAMA, COALESCE(SUM(JUMLAH), 0) TOTAL, COALESCE(SUM(CASE WHEN KATEGORI = 'PS' THEN JUMLAH END), 0) JUMLAH_PS,
				COALESCE(SUM(CASE WHEN KATEGORI = 'OPS' THEN JUMLAH END), 0) JUMLAH_OPS,
				COALESCE(SUM(CASE WHEN COALESCE(KATEGORI, '') = '' THEN JUMLAH END), 0) JUMLAH_INTERNAL
				FROM PPI_ASSET.pds_simpeg.AGAMA A 
				LEFT JOIN PPI_ASSET.(
									SELECT  AGAMA_ID, KATEGORI, COUNT(1) JUMLAH
									FROM PPI_ASSET.pds_simpeg.PEGAWAI A LEFT JOIN PPI_ASSET.PDS_SIMPEG.PEGAWAI_JABATAN_TERAKHIR B ON A.PEGAWAI_ID = B.PEGAWAI_ID
									WHERE 1 = 1  AND STATUS_PEGAWAI_ID = 1 ".$statement."
									GROUP BY KATEGORI, A.AGAMA_ID
								) B ON A.AGAMA_ID = B.AGAMA_ID
				WHERE A.AGAMA_ID IS NOT NULL
				GROUP BY A.AGAMA_ID, NAMA			
				"; 
		
		
		$str .= " ORDER BY A.AGAMA_ID ";
		$this->query = $str;
		return $this->selectLimit($str,-1,-1); 
    }

    function selectByParamsUnitKerja($statement="")
	{
		$str = "
				SELECT 0::INTEGER CABANG_P3_ID, 'Internal PDS'::VARCHAR NAMA, COUNT(1) TOTAL, 0::INTEGER JUMLAH_PS, 0::INTEGER JUMLAH_OPS
				FROM PPI_ASSET.PDS_SIMPEG.PEGAWAI WHERE KELOMPOK_PEGAWAI = 'D' AND STATUS_PEGAWAI_ID = 1
				UNION ALL
				SELECT A.CABANG_P3_ID, NAMA, COALESCE(SUM(JUMLAH), 0) TOTAL, COALESCE(SUM(CASE WHEN KATEGORI = 'PS' THEN JUMLAH END), 0) JUMLAH_PS,
								COALESCE(SUM(CASE WHEN KATEGORI = 'OPS' THEN JUMLAH END), 0) JUMLAH_OPS
				FROM
				(				
				SELECT A.CABANG_P3_ID, A.NAMA, C.KATEGORI, COUNT(1) JUMLAH 
				FROM PPI_ASSET.PDS_SIMPEG.CABANG_P3 A 
				INNER JOIN PPI_ASSET.PDS_SIMPEG.PEGAWAI_CABANG_P3_TERAKHIR B ON A.CABANG_P3_ID = B.CABANG_P3_ID
				INNER JOIN PPI_ASSET.PDS_SIMPEG.PEGAWAI_JABATAN_TERAKHIR C ON B.PEGAWAI_ID = C.PEGAWAI_ID
				INNER JOIN PPI_ASSET.PDS_SIMPEG.PEGAWAI D ON C.PEGAWAI_ID = D.PEGAWAI_ID AND STATUS_PEGAWAI_ID = 1
				INNER JOIN PPI_ASSET.PDS_SIMPEG.PEGAWAI_JENIS_PEGAWAI_TERAKHIR E ON D.PEGAWAI_ID = E.PEGAWAI_ID
				WHERE 1 = 1 ".$statement."
				GROUP BY A.CABANG_P3_ID, A.NAMA, C.KATEGORI
				ORDER BY A.CABANG_P3_ID
				) A 
				GROUP BY  A.CABANG_P3_ID, NAMA
				"; 
		
		
		$this->query = $str;
		return $this->selectLimit($str,-1,-1); 
    }

    function selectByParamsJenisPekerjaan($statement="")
	{
		$str = "
				SELECT A.JABATAN_ID, A.NAMA, COUNT(1) TOTAL FROM PPI_ASSET.PDS_SIMPEG.JABATAN A INNER JOIN
				PDS_SIMPEG.PEGAWAI_JABATAN_TERAKHIR B ON A.JABATAN_ID = B.JABATAN_ID INNER JOIN PPI_ASSET.
				PDS_SIMPEG.PEGAWAI C ON B.PEGAWAI_ID = C.PEGAWAI_ID AND STATUS_PEGAWAI_ID = 1 
				WHERE A.KELOMPOK = 'O' ".$statement."
				GROUP BY A.JABATAN_ID, A.NAMA
				ORDER BY A.KATEGORI, JABATAN_ID
				"; 
		
		
		$str .= "  ";
		$this->query = $str;
		return $this->selectLimit($str,-1,-1); 
    }

	function getCountByParamsJenisPekerjaan($statement="")
	{
		$str = "SELECT SUM(1) JUMLAH FROM PPI_ASSET.PDS_SIMPEG.JABATAN A INNER JOIN
				PDS_SIMPEG.PEGAWAI_JABATAN_TERAKHIR B ON A.JABATAN_ID = B.JABATAN_ID INNER JOIN
				PDS_SIMPEG.PEGAWAI C ON B.PEGAWAI_ID = C.PEGAWAI_ID AND STATUS_PEGAWAI_ID = 1
				WHERE A.KELOMPOK = 'O' ".$statement;
		
		$this->select($str);
		$this->query = $str; 
		if($this->firstRow()) 
			return $this->getField("JUMLAH"); 
		else 
			return 0; 
    }
			
    function selectByParamsKelamin($statement)
	{
		$str = "SELECT A.JENIS_KELAMIN IDKETERANGAN, CASE WHEN A.JENIS_KELAMIN = 'P' THEN 'Perempuan' WHEN A.JENIS_KELAMIN = 'L' THEN 'Laki-laki' ELSE ' ' END NAMA, 
				COALESCE(COUNT(1), 0) TOTAL, COALESCE(COUNT(CASE WHEN KATEGORI = 'PS' THEN 1 END), 0) JUMLAH_PS,
				COALESCE(COUNT(CASE WHEN KATEGORI = 'OPS' THEN 1 END), 0) JUMLAH_OPS,
				COALESCE(COUNT(CASE WHEN COALESCE(KATEGORI, '') = '' THEN 1 END), 0) JUMLAH_INTERNAL
									FROM PPI_ASSET.pds_simpeg.PEGAWAI A LEFT JOIN PPI_ASSET.PDS_SIMPEG.PEGAWAI_JABATAN_TERAKHIR B ON A.PEGAWAI_ID = B.PEGAWAI_ID
									WHERE 1 = 1 AND STATUS_PEGAWAI_ID = 1  ".$statement."
									GROUP BY A.JENIS_KELAMIN 
				"; 
		
		
		$str .= " ORDER BY A.JENIS_KELAMIN ";
		$this->query = $str;
		return $this->selectLimit($str,-1,-1); 
    }

    function selectByParamsPendidikan($statement)
	{
		$str = "SELECT A.PENDIDIKAN_ID, NAMA, COALESCE(SUM(JUMLAH), 0) TOTAL, COALESCE(SUM(CASE WHEN KATEGORI = 'PS' THEN JUMLAH END), 0) JUMLAH_PS,
				COALESCE(SUM(CASE WHEN KATEGORI = 'OPS' THEN JUMLAH END), 0) JUMLAH_OPS,
				COALESCE(SUM(CASE WHEN COALESCE(KATEGORI, '') = '' THEN JUMLAH END), 0) JUMLAH_INTERNAL
				FROM PPI_ASSET.pds_simpeg.PENDIDIKAN A 
				LEFT JOIN PPI_ASSET.(
									SELECT  B.PENDIDIKAN_ID, C.KATEGORI, COUNT(1) JUMLAH
									FROM PPI_ASSET.pds_simpeg.PEGAWAI A 
									LEFT JOIN PPI_ASSET.(SELECT PEGAWAI_ID, PENDIDIKAN_ID FROM PPI_ASSET.pds_simpeg.PEGAWAI_PENDIDIKAN) B ON A.PEGAWAI_ID = B.PEGAWAI_ID 
									LEFT JOIN PPI_ASSET.pds_simpeg.PEGAWAI_JABATAN_TERAKHIR C ON A.PEGAWAI_ID = C.PEGAWAI_ID
									WHERE STATUS_PEGAWAI_ID = 1 ".$statement."
									GROUP BY B.PENDIDIKAN_ID, C.KATEGORI
								) B ON A.PENDIDIKAN_ID = B.PENDIDIKAN_ID
				WHERE A.PENDIDIKAN_ID IS NOT NULL 
			GROUP BY A.PENDIDIKAN_ID, NAMA	   
				"; 
		
		
		$str .= " ORDER BY A.PENDIDIKAN_ID::NUMERIC ASC ";
		$this->query = $str;
		return $this->selectLimit($str,-1,-1); 
    }

    function selectByParamsUsia($statement)
	{
		$str = "
			SELECT '30' IDKETERANGAN, '<= 30' NAMA, COALESCE(SUM(JUMLAH), 0) TOTAL, COALESCE(SUM(CASE WHEN KATEGORI = 'PS' THEN JUMLAH END), 0) JUMLAH_PS,
				COALESCE(SUM(CASE WHEN KATEGORI = 'OPS' THEN JUMLAH END), 0) JUMLAH_OPS,
				COALESCE(SUM(CASE WHEN COALESCE(KATEGORI, '') = '' THEN JUMLAH END), 0) JUMLAH_INTERNAL
							FROM PPI_ASSET.(
								SELECT KATEGORI, COUNT(A.PEGAWAI_ID) JUMLAH
								FROM PPI_ASSET.pds_simpeg.PEGAWAI  A, (
									SELECT X.PEGAWAI_ID, REPLACE(PDS_SIMPEG.AMBIL_MASA_KERJA(TANGGAL_LAHIR, CURRENT_DATE), ',', '.')::NUMERIC AS USIA, KATEGORI
										FROM PPI_ASSET.pds_simpeg.PEGAWAI  X LEFT JOIN PPI_ASSET.pds_simpeg.PEGAWAI_JABATAN_TERAKHIR Y ON X.PEGAWAI_ID = Y.PEGAWAI_ID
									) B
								WHERE STATUS_PEGAWAI_ID = 1 AND A.PEGAWAI_ID = B.PEGAWAI_ID AND B.USIA < 31::NUMERIC ".$statement."
								GROUP BY KATEGORI
							) Y   
			UNION ALL				
			SELECT '3135' IDKETERANGAN, '31 - 35' NAMA, COALESCE(SUM(JUMLAH), 0) TOTAL, COALESCE(SUM(CASE WHEN KATEGORI = 'PS' THEN JUMLAH END), 0) JUMLAH_PS,
				COALESCE(SUM(CASE WHEN KATEGORI = 'OPS' THEN JUMLAH END), 0) JUMLAH_OPS,
				COALESCE(SUM(CASE WHEN COALESCE(KATEGORI, '') = '' THEN JUMLAH END), 0) JUMLAH_INTERNAL
							FROM PPI_ASSET.(
								SELECT KATEGORI, COUNT(A.PEGAWAI_ID) JUMLAH
								FROM PPI_ASSET.pds_simpeg.PEGAWAI  A, (
									SELECT X.PEGAWAI_ID, REPLACE(PDS_SIMPEG.AMBIL_MASA_KERJA(TANGGAL_LAHIR, CURRENT_DATE), ',', '.')::NUMERIC AS USIA, KATEGORI
										FROM PPI_ASSET.pds_simpeg.PEGAWAI  X LEFT JOIN PPI_ASSET.pds_simpeg.PEGAWAI_JABATAN_TERAKHIR Y ON X.PEGAWAI_ID = Y.PEGAWAI_ID
									) B
								WHERE STATUS_PEGAWAI_ID = 1 AND A.PEGAWAI_ID = B.PEGAWAI_ID AND B.USIA >= 31::NUMERIC AND B.USIA < 36::NUMERIC ".$statement."
								GROUP BY KATEGORI
							) Y     
			UNION ALL				
			SELECT '3640' IDKETERANGAN, '36 - 40' NAMA, COALESCE(SUM(JUMLAH), 0) TOTAL, COALESCE(SUM(CASE WHEN KATEGORI = 'PS' THEN JUMLAH END), 0) JUMLAH_PS,
				COALESCE(SUM(CASE WHEN KATEGORI = 'OPS' THEN JUMLAH END), 0) JUMLAH_OPS,
				COALESCE(SUM(CASE WHEN COALESCE(KATEGORI, '') = '' THEN JUMLAH END), 0) JUMLAH_INTERNAL
							FROM PPI_ASSET.(
								SELECT KATEGORI, COUNT(A.PEGAWAI_ID) JUMLAH
								FROM PPI_ASSET.pds_simpeg.PEGAWAI  A, (
									SELECT X.PEGAWAI_ID, REPLACE(PDS_SIMPEG.AMBIL_MASA_KERJA(TANGGAL_LAHIR, CURRENT_DATE), ',', '.')::NUMERIC AS USIA, KATEGORI
										FROM PPI_ASSET.pds_simpeg.PEGAWAI  X LEFT JOIN PPI_ASSET.pds_simpeg.PEGAWAI_JABATAN_TERAKHIR Y ON X.PEGAWAI_ID = Y.PEGAWAI_ID
									) B
								WHERE STATUS_PEGAWAI_ID = 1 AND A.PEGAWAI_ID = B.PEGAWAI_ID AND B.USIA >= 36::NUMERIC AND B.USIA < 41::NUMERIC ".$statement."
								GROUP BY KATEGORI
							) Y   
			UNION ALL				
			SELECT '4145' IDKETERANGAN, '41 - 45' NAMA, COALESCE(SUM(JUMLAH), 0) TOTAL, COALESCE(SUM(CASE WHEN KATEGORI = 'PS' THEN JUMLAH END), 0) JUMLAH_PS,
				COALESCE(SUM(CASE WHEN KATEGORI = 'OPS' THEN JUMLAH END), 0) JUMLAH_OPS,
				COALESCE(SUM(CASE WHEN COALESCE(KATEGORI, '') = '' THEN JUMLAH END), 0) JUMLAH_INTERNAL
							FROM PPI_ASSET.(
								SELECT KATEGORI, COUNT(A.PEGAWAI_ID) JUMLAH
								FROM PPI_ASSET.pds_simpeg.PEGAWAI  A, (
									SELECT X.PEGAWAI_ID, REPLACE(PDS_SIMPEG.AMBIL_MASA_KERJA(TANGGAL_LAHIR, CURRENT_DATE), ',', '.')::NUMERIC AS USIA, KATEGORI
										FROM PPI_ASSET.pds_simpeg.PEGAWAI  X LEFT JOIN PPI_ASSET.pds_simpeg.PEGAWAI_JABATAN_TERAKHIR Y ON X.PEGAWAI_ID = Y.PEGAWAI_ID
									) B
								WHERE STATUS_PEGAWAI_ID = 1 AND A.PEGAWAI_ID = B.PEGAWAI_ID AND B.USIA >= 41::NUMERIC AND B.USIA < 46::NUMERIC ".$statement."
								GROUP BY KATEGORI
							) Y    
			UNION ALL				
			SELECT '4650' IDKETERANGAN, '46 - 50' NAMA, COALESCE(SUM(JUMLAH), 0) TOTAL, COALESCE(SUM(CASE WHEN KATEGORI = 'PS' THEN JUMLAH END), 0) JUMLAH_PS,
				COALESCE(SUM(CASE WHEN KATEGORI = 'OPS' THEN JUMLAH END), 0) JUMLAH_OPS,
				COALESCE(SUM(CASE WHEN COALESCE(KATEGORI, '') = '' THEN JUMLAH END), 0) JUMLAH_INTERNAL
							FROM PPI_ASSET.(
								SELECT KATEGORI, COUNT(A.PEGAWAI_ID) JUMLAH
								FROM PPI_ASSET.pds_simpeg.PEGAWAI  A, (
									SELECT X.PEGAWAI_ID, REPLACE(PDS_SIMPEG.AMBIL_MASA_KERJA(TANGGAL_LAHIR, CURRENT_DATE), ',', '.')::NUMERIC AS USIA, KATEGORI
										FROM PPI_ASSET.pds_simpeg.PEGAWAI  X LEFT JOIN PPI_ASSET.pds_simpeg.PEGAWAI_JABATAN_TERAKHIR Y ON X.PEGAWAI_ID = Y.PEGAWAI_ID
									) B
								WHERE STATUS_PEGAWAI_ID = 1 AND A.PEGAWAI_ID = B.PEGAWAI_ID AND B.USIA >= 46::NUMERIC AND B.USIA <= 50::NUMERIC ".$statement."
								GROUP BY KATEGORI
							) Y     
			UNION ALL		
			SELECT '50' IDKETERANGAN, '> 50' NAMA, COALESCE(SUM(JUMLAH), 0) TOTAL, COALESCE(SUM(CASE WHEN KATEGORI = 'PS' THEN JUMLAH END), 0) JUMLAH_PS,
				COALESCE(SUM(CASE WHEN KATEGORI = 'OPS' THEN JUMLAH END), 0) JUMLAH_OPS,
				COALESCE(SUM(CASE WHEN COALESCE(KATEGORI, '') = '' THEN JUMLAH END), 0) JUMLAH_INTERNAL
							FROM PPI_ASSET.(
								SELECT KATEGORI, COUNT(A.PEGAWAI_ID) JUMLAH
								FROM PPI_ASSET.pds_simpeg.PEGAWAI  A, (
									SELECT X.PEGAWAI_ID, REPLACE(PDS_SIMPEG.AMBIL_MASA_KERJA(TANGGAL_LAHIR, CURRENT_DATE), ',', '.')::NUMERIC AS USIA, KATEGORI
										FROM PPI_ASSET.pds_simpeg.PEGAWAI  X LEFT JOIN PPI_ASSET.pds_simpeg.PEGAWAI_JABATAN_TERAKHIR Y ON X.PEGAWAI_ID = Y.PEGAWAI_ID
									) B
								WHERE STATUS_PEGAWAI_ID = 1 AND A.PEGAWAI_ID = B.PEGAWAI_ID AND B.USIA > 50::NUMERIC ".$statement."
								GROUP BY KATEGORI
							) Y      	   
				"; 
		
		
		$str .= "  ";
		$this->query = $str;
		return $this->selectLimit($str,-1,-1); 
    }

    function selectByParamsKategori($statement)
	{
		$str = "SELECT A.KATEGORI_ID, A.NAMA, COALESCE(JUMLAH, 0) JUMLAH
				FROM PPI_ASSET.KATEGORI  A 
				LEFT JOIN PPI_ASSET.(
									SELECT  A.KATEGORI_ID, COUNT(1) JUMLAH
									FROM PPI_ASSET.ARSIP A
									WHERE 1 = 1 ".$statement."
									GROUP BY A.KATEGORI_ID                                    
                                ) B ON A.KATEGORI_ID = B.KATEGORI_ID
                WHERE A.KATEGORI_ID IS NOT NULL AND A.NAMA IS NOT NULL 
				"; 
		
		
		$str .= " ORDER BY A.KATEGORI_ID ";
		$this->query = $str;
		return $this->selectLimit($str,-1,-1); 
    }
		
  } 
?>