<? 
/* *******************************************************************************************************
MODUL NAME 			: SIMWEB
FILE NAME 			: LogPengunjung.php
AUTHOR				: MRF
VERSION				: 1.0
MODIFICATION DOC	:
DESCRIPTION			: Entity-base class for tabel Log_Pengunjung implementation
***************************************************************************************************** */

  /***
  * Entity-class untuk mengimplementasikan tabel log_pengunjung.
  * 
  * @author M Reza Faisal
  * @generated by Entity Generator 5.8.3
  * @generated on 21-Apr-2005,13:47
  ***/
  include_once("../WEB-INF/classes/base/LogPengunjungBase.php");

  class LogPengunjung extends LogPengunjungBase{ 

    /************************** <STANDARD METHODS> **************************************/
    /**
    * Class constructor.
    * @author M Reza Faisal
    **/
    function LogPengunjung(){
      /** !!DO NOT REMOVE/CHANGE CODES IN THIS SECTION!! **/
      $this->LogPengunjungBase(); //execute Entity constructor
      /** YOU CAN INSERT/CHANGE CODES IN THIS SECTION **/				
			
	
    }

    /************************** </STANDARD METHODS> **********************************/

    /************************** <ADDITIONAL METHODS> *********************************/


    /************************** </ADDITIONAL METHODS> *******************************/
  } //end of class LogPengunjung
?>